---
editor_options:
  chunk_output_type: console
---
```{r ddm-descriptive-setup}
# Library calls
library(brms)
library(tidyverse)
library(tidybayes)
library(emmeans)
library(loo)
```

```{r ddm-descriptive-functions}
prep_drift <- function(data){
  data %>% 
    filter(param == "drift")
}

prep_bs <- function(data){
  data %>% 
    filter(param == "bs")
}

prep_ndt <- function(data){
  data %>% filter(param == "ndt")
}

prep_bias <- function(data){
  data %>% 
    filter(param == "bias")
}

plot_robust <- function(data){
  data %>% 
    ggplot(
      aes(
        x = error_factor,
        y = mean
      )
    )+
  geom_point()+
    # geom_bar(stat = "identity", position = "dodge", width = 0.6)+
    geom_errorbar(
      aes(
        ymin = upper, 
        ymax = lower, 
        width = 0.2
      ),
    )+
    labs(
      y = "estimate",
      x = ""
    )+
    theme_classic()+
    theme(text =element_text(size=20))
}
```

```{r ddm-descriptive-data, cache = TRUE}
# Reading in data 
fit_robust <- rio::import("./markdown/diffusion_model_runs/cluster/output/hierarch_model_long_robust.rda")
```

```{r ddm-descriptive-counting-location}
model_robust_count <- fit_robust$data %>% 
  count(id, error_factor) %>%
  group_by(error_factor) %>% 
  summarize(
    median = median(n),
    sd = sd(n),
    total = sum(n)
  )

model_classic_count

model_speed_count

```

```{r ddm-descriptive-table-params}
table <- fixef(fit_robust) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5) %>% 
  filter(str_detect(param, "rsilong"))
```

```{r ddm-descriptive-robust, cache = TRUE, eval = FALSE}
data_robust <- fixef(fit_robust) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5)


working_robust <- data_robust %>% 
  mutate(param = str_replace(param, "^error_factor", "drift_error_factor")) %>% 
  mutate(
    param = str_remove(param, "error_factor"),
    param = str_remove(param, "_error$")
  ) %>% 
  separate(
    param,
    into = c("param", "error_factor"),
    sep = "_"
  ) %>% 
  mutate(error_factor = paste0(error_factor, "-error")) %>% 
  mutate(error_factor = factor(error_factor)) %>% 
  mutate(error_factor = fct_relevel(error_factor, "pre-error", "post-error"))
 
summary_robust <- working_robust

drift_robust_plot <- summary_robust %>%
  prep_drift() %>%
  plot_robust()

ndt_robust_plot <- summary_robust %>% 
  prep_ndt() %>% 
  plot_robust()

bs_robust_plot <- summary_robust %>% 
  prep_bs() %>% 
  plot_robust()

bias_robust_plot <- summary_robust %>% 
  prep_bias() %>% 
  plot_robust()
```

```{r ddm-descriptive-classic, cache = TRUE, eval = FALSE}
data_classic <- fixef(fit_classic) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5)


working_classic <- data_classic %>% 
  mutate(param = str_replace(param, "previous_stimulus", "prevstim")) %>% 
  mutate(param = str_replace(param, "^rsi", "drift_rsi")) %>% 
  # filter(!str_detect(param, "bias")) %>% 
  separate(param,
           into = c("rsi", "error_factor", "stimulus"),
           sep = ":") %>% 
  # mutate(rsi = ifelse(str_detect(rsi, "^rsi"), paste0("drift_", rsi), rsi)) %>% 
  separate(
    rsi,
    into = c("param", "rsi"),
    sep = "_"
  )
working_classic[which(working_classic$param == "bias"), c("error_factor", "stimulus")] <- working_classic[which(working_classic$param == "bias"), c("stimulus", "error_factor")]
 
summary_classic <- working_classic %>% 
  mutate(
    rsi = str_remove(rsi, "rsi"),
    error_factor = str_remove(error_factor, "error_factor"),
    stimulus = str_remove(stimulus, "stimulus")
  ) %>% 
  mutate(
    location = error_factor
  ) %>% 
  mutate(mean_corrected = abs(mean), lower_corrected = abs(lower), upper_corrected = abs(upper)) %>% 
  group_by(param, rsi, location, stimulus) %>% 
  summarize(
    mean = mean(mean_corrected),
    lower = mean(lower_corrected), 
    upper = mean(upper_corrected)
    )

drift_classic_rsi_plot <- summary_classic %>%
  filter(param == "drift") %>%
  group_by(rsi, location) %>%
  summarize(
    mean = mean(mean),
    upper = mean(upper),
    lower = mean(lower)
  ) %>%
  plot_params_classic()

drift_classic_long_rsi <- summary_classic %>% 
  filter(param == "drift") %>% 
  group_by(rsi, location) %>%
  summarize(
    mean = mean(mean),
    upper = mean(upper),
    lower = mean(lower)
  ) %>%
  plot_long_rsi_classic()

bs_classic_rsi_plot <- summary_classic %>%
  filter(param == "bs") %>%
  plot_params_classic()

bs_classic_long_rsi <- summary_classic %>% 
  filter(param == "bs") %>% 
  plot_long_rsi_classic()

ndt_classic_rsi_plot <- summary_classic %>%
  filter(param == "ndt") %>%
  plot_params_classic()

ndt_classic_long_rsi <- summary_classic %>% 
  filter(param == "ndt") %>% 
  plot_long_rsi_classic()

bias_classic_rsi_plot <- summary_classic %>%
    %>%
  plot_params_classic()

bias_classic_err_plot <- summary_classic %>%
  filter(param == "bias") %>%
  mutate(
    lower_copy = lower,
    upper_copy = upper,
    mean = ifelse(
      stimulus == "prevstimX",
      1 - mean,
      mean
    ),
    upper = ifelse(
      stimulus == "prevstimX",
      1 - lower_copy, # need to turn this around for inversion
      upper
    ),
    lower = ifelse(
      stimulus == "prevstimX",
      1 - upper_copy,
      lower
    )
  ) %>%
  select(-ends_with("copy")) %>%
  group_by(location, rsi) %>%
  summarize(mean = mean(mean),
            upper = mean(upper),
            lower = mean(lower))  %>%
  plot_post_error()

bias_classic_long_rsi <- summary_classic %>%
  filter(param == "bias") %>%
  mutate(
    lower_copy = lower,
    upper_copy = upper,
    mean = ifelse(
      stimulus == "prevstimX",
      1 - mean,
      mean
    ),
    upper = ifelse(
      stimulus == "prevstimX",
      1 - lower_copy, # need to turn this around for inversion
      upper
    ),
    lower = ifelse(
      stimulus == "prevstimX",
      1 - upper_copy,
      lower
    )
  ) %>%
  select(-ends_with("copy")) %>%
  group_by(location, rsi) %>%
  summarize(mean = mean(mean),
            upper = mean(upper),
            lower = mean(lower))  %>%
  plot_long_rsi_classic()
```

