---
editor_options:
  chunk_output_type: console
---
```{r ddm-significance-setup, include = FALSE}
# Library calls
library(brms)
library(tidyverse)
library(tidybayes)
library(emmeans)
library(loo)
library(BayesFactor)
# library(effectsize)
library(effsize)
library(bayestestR)
```

```{r ddm-significance-functions}
# Custom functions
calculate_evidence <- function(bs, bias){
  bs = abs(bs)
  start = bs * bias
  distance = bs - start
  return(distance)
}

return_d_value <- function(mu1, mu2, sd1, sd2){
  pooled_sd = sqrt(0.5*(sd1^2 + sd2^2))
  diff_means = mu1 - mu2
  cohens_d = diff_means/pooled_sd
  return(cohens_d)
}
```

```{r ddm-significance-data, cache = TRUE}
# Reading in data 
fit_robust <- rio::import("./markdown/diffusion_model_runs/cluster/output/hierarch_model_long_robust.rda")

fit_speed <- rio::import("./markdown/diffusion_model_runs/cluster/output/hierarch_model_speeding.rda")

fit_classic <- rio::import("./markdown/diffusion_model_runs/cluster/output/hierarch_model_long_classic.rda")


posterior_robust <- as_draws_df(
  fit_robust
)

posterior_speed <- as_draws_df(
  fit_speed
)

posterior_classic <- as_draws_df(
  fit_classic
)
```
```{r signif-adding-d-value, cache = TRUE}
posterior_robust$cohens_d_drift = NA
posterior_robust$cohens_d_bs = NA
posterior_robust$cohens_d_bias = NA
posterior_robust$cohens_d_ndt = NA

for (row in 1:nrow(posterior_robust)) {
  posterior_robust$cohens_d_drift[row] = return_d_value(
    posterior_robust$b_error_factorpost_error[row],
    posterior_robust$b_error_factorpre_error[row],
    posterior_robust$sd_id__error_factorpost_error[row],
    posterior_robust$sd_id__error_factorpre_error[row]
  )
  posterior_robust$cohens_d_bs[row] = return_d_value(
    posterior_robust$b_bs_error_factorpost_error[row],
    posterior_robust$b_bs_error_factorpre_error[row],
    posterior_robust$sd_id__bs_error_factorpost_error[row],
    posterior_robust$sd_id__bs_error_factorpre_error[row]
  )
  posterior_robust$cohens_d_ndt[row] = return_d_value(
    posterior_robust$b_ndt_error_factorpost_error[row],
    posterior_robust$b_ndt_error_factorpre_error[row],
    posterior_robust$sd_id__ndt_error_factorpost_error[row],
    posterior_robust$sd_id__ndt_error_factorpre_error[row]
  )
  posterior_robust$cohens_d_bias[row] = return_d_value(
    posterior_robust$b_bias_error_factorpost_error[row],
    posterior_robust$b_bias_error_factorpre_error[row],
    posterior_robust$sd_id__bias_error_factorpost_error[row],
    posterior_robust$sd_id__bias_error_factorpre_error[row]
  )
}

cohens_d_robust_drift_mean_d = mean(posterior_robust$cohens_d_drift)
cohens_d_robust_bs_mean_d = mean(posterior_robust$cohens_d_bs)
cohens_d_robust_ndt_mean_d = mean(posterior_robust$cohens_d_ndt)
cohens_d_robust_bias_mean_d = mean(posterior_robust$cohens_d_bias)

posterior_classic$cohens_d_drift = NA
posterior_classic$cohens_d_bs = NA
posterior_classic$cohens_d_bias = NA
posterior_classic$cohens_d_ndt = NA

for (row in 1:nrow(posterior_classic)) {
  posterior_classic$cohens_d_drift[row] = return_d_value(
    posterior_classic$b_error_factorpost_error[row],
    posterior_classic$b_error_factorpost_correct[row],
    posterior_classic$sd_id__error_factorpost_error[row],
    posterior_classic$sd_id__error_factorpost_correct[row]
  )
  posterior_classic$cohens_d_bs[row] = return_d_value(
    posterior_classic$b_bs_error_factorpost_error[row],
    posterior_classic$b_bs_error_factorpost_correct[row],
    posterior_classic$sd_id__bs_error_factorpost_error[row],
    posterior_classic$sd_id__bs_error_factorpost_correct[row]
  )
  posterior_classic$cohens_d_ndt[row] = return_d_value(
    posterior_classic$b_ndt_error_factorpost_error[row],
    posterior_classic$b_ndt_error_factorpost_correct[row],
    posterior_classic$sd_id__ndt_error_factorpost_error[row],
    posterior_classic$sd_id__ndt_error_factorpost_correct[row]
  )
  posterior_classic$cohens_d_bias[row] = return_d_value(
    posterior_classic$b_bias_error_factorpost_error[row],
    posterior_classic$b_bias_error_factorpost_correct[row],
    posterior_classic$sd_id__bias_error_factorpost_error[row],
    posterior_classic$sd_id__bias_error_factorpost_correct[row]
  )
}

cohens_d_classic_drift_mean_d = mean(posterior_classic$cohens_d_drift)
cohens_d_classic_bs_mean_d = mean(posterior_classic$cohens_d_bs)
cohens_d_classic_ndt_mean_d = mean(posterior_classic$cohens_d_ndt)
cohens_d_classic_bias_mean_d = mean(posterior_classic$cohens_d_bias)

```

```{r testing-robust-drift, cache = TRUE}
# Testing drift
posterior_robust_drift <- posterior_robust %>% 
  select(starts_with("b_error"))

colnames(posterior_robust_drift) <- c("post_error", "pre_error")

t_test_robust_drift <- t.test(posterior_robust_drift$pre_error, posterior_robust_drift$post_error)

bf_robust_drift <- bf_pointnull(posterior_robust_drift$post_error - posterior_robust_drift$pre_error, prior = distribution_normal(nrow(posterior_robust_drift), 0, sd(rnorm(nrow(posterior_robust_drift), 0, 5) - rnorm(nrow(posterior_robust_drift), 0, 5))))

cohens_d_robust_drift <- cohen.d(posterior_robust_drift$pre_error, posterior_robust_drift$post_error)
```

```{r testing-robust-bs, cache = TRUE}
# Testing drift
posterior_robust_bs <- posterior_robust %>% 
  select(starts_with("b_bs_error"))

colnames(posterior_robust_bs) <- c("post_error", "pre_error")

t_test_robust_bs <- t.test(posterior_robust_bs$pre_error, posterior_robust_bs$post_error)

bf_robust_bs <- bf_pointnull(posterior_robust_bs$post_error - posterior_robust_bs$pre_error, prior = distribution_normal(nrow(posterior_robust_bs), 0, sd(rgamma(nrow(posterior_robust_bs), 10, 5) - rgamma(nrow(posterior_robust_bs), 10, 5))))

cohens_d_robust_bs <- cohen.d(posterior_robust_bs$pre_error, posterior_robust_bs$post_error)
```

```{r testing-robust-ndt, cache = TRUE}
posterior_robust_ndt <- posterior_robust %>% 
  select(starts_with("b_ndt_error"))

colnames(posterior_robust_ndt) <- c("post_error", "pre_error")

t_test_robust_ndt <- t.test(posterior_robust_ndt$pre_error, posterior_robust_ndt$post_error)

bf_robust_ndt <- bf_pointnull(posterior_robust_ndt$post_error - posterior_robust_ndt$pre_error, prior = distribution_normal(nrow(posterior_robust_ndt), 0, sd(rgamma(nrow(posterior_robust_ndt), 1, 5) - rgamma(nrow(posterior_robust_ndt), 1, 5))))

cohens_d_robust_ndt <- cohen.d(posterior_robust_ndt$pre_error, posterior_robust_ndt$post_error)
```

```{r testing-robust-bias, cache = TRUE}
# Testing drift
posterior_robust_bias <- posterior_robust %>% 
  select(starts_with("b_bias_error"))

colnames(posterior_robust_bias) <- c("post_error",
                                     "pre_error")

t_test_robust_bias <- t.test(posterior_robust_bias$pre_error, posterior_robust_bias$post_error, paired = TRUE)

bf_robust_bias <- bf_pointnull(posterior_robust_bias$post_error - posterior_robust_bias$pre_error, prior = distribution_normal(nrow(posterior_robust_bias), 0, sd(rbeta(nrow(posterior_robust_bias), 4, 4) - rbeta(nrow(posterior_robust_bias), 4, 4))))

cohens_d_robust_bias <- cohen.d(posterior_robust_bias$pre_error, posterior_robust_bias$post_error)
```

```{r testing-evidece-robust, cache = TRUE}
posterior_robust_evidence <- posterior_robust %>% 
  mutate(
    evidence_pre_error = calculate_evidence(
      posterior_robust$b_bs_error_factorpre_error,
      posterior_robust$b_bias_error_factorpre_error
    ),
    evidence_post_error = calculate_evidence(
      posterior_robust$b_bs_error_factorpost_error,
      posterior_robust$b_bias_error_factorpost_error
    )
  ) %>% 
  select(starts_with("evidence"))

t_test_robust_evidence <- t.test(posterior_robust_evidence$evidence_pre_error,
                                 posterior_robust_evidence$evidence_post_error)
cohens_d_robust_evidence <- cohen.d(posterior_robust_evidence$evidence_pre_error,
                                 posterior_robust_evidence$evidence_post_error)
```

```{r testing-classic-drift, cache = TRUE}
# Testing drift
posterior_classic_drift <- posterior_classic %>% 
  select(starts_with("b_error"))

colnames(posterior_classic_drift) <- c("post_correct", "post_error")

t_test_classic_drift <- t.test(posterior_classic_drift$post_correct, posterior_classic_drift$post_error)

bf_classic_drift <- bf_pointnull(posterior_classic_drift$post_error - posterior_classic_drift$post_correct, prior = distribution_normal(nrow(posterior_classic_drift), 0, sd(rnorm(nrow(posterior_classic_drift), 0, 5) - rnorm(nrow(posterior_classic_drift), 0, 5))))

cohens_d_classic_drift <- cohen.d(posterior_classic_drift$post_correct, posterior_classic_drift$post_error)
```

```{r testing-classic-bs, cache = TRUE}
# Testing drift
posterior_classic_bs <- posterior_classic %>% 
  select(starts_with("b_bs_error"))

colnames(posterior_classic_bs) <- c("post_correct", "post_error")

t_test_classic_bs <- t.test(posterior_classic_bs$post_correct, posterior_classic_bs$post_error)

bf_classic_bs <- bf_pointnull(posterior_classic_bs$post_error - posterior_classic_bs$post_correct, prior = distribution_normal(nrow(posterior_classic_bs), 0, sd(rgamma(nrow(posterior_classic_bs), 10, 5) - rgamma(nrow(posterior_classic_bs), 10, 5))))

cohens_d_classic_bs <- cohen.d(posterior_classic_bs$post_correct, posterior_classic_bs$post_error)
```

```{r testing-classic-ndt, cache = TRUE}
posterior_classic_ndt <- posterior_classic %>% 
  select(starts_with("b_ndt_error"))

colnames(posterior_classic_ndt) <- c("post_correct", "post_error")

t_test_classic_ndt <- t.test(posterior_classic_ndt$post_correct, posterior_classic_ndt$post_error)

bf_classic_ndt <- bf_pointnull(posterior_classic_ndt$post_error - posterior_classic_ndt$post_correct, prior = distribution_normal(nrow(posterior_classic_ndt), 0, sd(rgamma(nrow(posterior_classic_ndt), 1, 5) - rgamma(nrow(posterior_classic_ndt), 1, 5))))

cohens_d_classic_ndt <- cohen.d(posterior_classic_ndt$post_correct, posterior_classic_ndt$post_error)
```

```{r testing-classic-bias, cache = TRUE}
# Testing drift
posterior_classic_bias <- posterior_classic %>% 
  select(starts_with("b_bias_error"))

colnames(posterior_classic_bias) <- c("post_correct", "post_error")

t_test_classic_bias <- t.test(posterior_classic_bias$post_correct, posterior_classic_bias$post_error)

bf_classic_bias <- bf_pointnull(posterior_classic_bias$post_error - posterior_classic_bias$post_correct, prior = distribution_normal(nrow(posterior_classic_bias), 0, sd(rbeta(nrow(posterior_classic_bias), 4, 4) - rbeta(nrow(posterior_classic_bias), 4, 4))))

cohens_d_classic_bias <- cohen.d(posterior_classic_bias$post_correct, posterior_classic_bias$post_error)

```


```{r testing-speed-drift, cache = TRUE}
# Testing drift
posterior_speed_drift <- posterior_speed %>% 
  select(starts_with("b_error"))

colnames(posterior_speed_drift) <- c("pre_correct", "pre_error")

t_test_speed_drift <- t.test(posterior_speed_drift$pre_correct, posterior_speed_drift$pre_error)

cohens_d_speed_drift <- cohen.d(posterior_speed_drift$pre_correct, posterior_speed_drift$pre_error)
```

```{r testing-speed-bs, cache = TRUE}
# Testing drift
posterior_speed_bs <- posterior_speed %>% 
  select(starts_with("b_bs_error"))

colnames(posterior_speed_bs) <- c("pre_correct", "pre_error")

t_test_speed_bs <- t.test(posterior_speed_bs$pre_correct, posterior_speed_bs$pre_error)

cohens_d_speed_bs <- cohen.d(posterior_speed_bs$pre_correct, posterior_speed_bs$pre_error)
```

```{r testing-speed-ndt, cache = TRUE}
posterior_speed_ndt <- posterior_speed %>% 
  select(starts_with("b_ndt_error"))

colnames(posterior_speed_ndt) <- c("pre_correct", "pre_error")

t_test_speed_ndt <- t.test(posterior_speed_ndt$pre_correct, posterior_speed_ndt$pre_error)

cohens_d_speed_ndt <- cohen.d(posterior_speed_ndt$pre_correct, posterior_speed_ndt$pre_error)
```

```{r testing-speed-bias, cache = TRUE}
# Testing drift
posterior_speed_bias <- posterior_speed %>% 
  select(starts_with("b_bias_error"))

colnames(posterior_speed_bias) <- c("pre_correct", "pre_error")

t_test_speed_bias <- t.test(posterior_speed_bias$pre_correct, posterior_speed_bias$pre_error)

cohens_d_speed_bias <- cohen.d(posterior_speed_bias$pre_correct, posterior_speed_bias$pre_error)

```
