---
editor_options:
  chunk_output_type: console
---
```{r setup}
# Library calls
library(brms)
library(tidyverse)
library(gridExtra) # for grid.arrange
library(DescTools) # for CCC
library(dtplyr)
```

```{r functions}
# Custom functions
min_ess <- function(model){
  model$fit %>% 
  rstan::summary() %>% 
  .$summary %>% 
  as_tibble() %>% 
  slice_min(n_eff, n = 5)
}

max_rhat <- function(model){
  model$fit %>% 
  rstan::summary() %>% 
  .$summary %>% 
  as_tibble() %>% 
  slice_max(Rhat, n = 5)
}

n_divergent <- function(model){
  sum(subset(nuts_params(model), Parameter=="divergent__")$Value)
}

inspect_pars <- function(model){
  pars = variables(model)
  pars_sel = c(
  sample(pars[1:(length(pars)/2)], 3),
  sample(pars[-(1:(length(pars)/2))], 3)
  )

  return(
    plot(model, variable = pars_sel, N = 6, 
     ask = FALSE, exact_match = TRUE, newpage = TRUE, plot = TRUE)
  )
}

get_max_cors <- function(model){
  posterior = as.mcmc(model, combine_chains = TRUE)
  cor_posterior = cor(posterior)
  cor_posterior[lower.tri(cor_posterior, diag = TRUE)] = NA
  cor_long = as.data.frame(as.table(cor_posterior))
  cor_long = na.omit(cor_long)
  print(tail(cor_long[order(abs(cor_long$Freq)),], 10))
  
  hist(cor_long$Freq, breaks = 40)
}


```

```{r data}
# Reading in data
fit_wiener_robust <- rio::import("./markdown/models/robust_standard_rsi_err2023-02-15.rda")
fit_wiener_classic <- rio::import("./markdown/models/classic_standard_rsi_err_2023-02-15.rda")
fit_wiener_location <- rio::import("./markdown/models/location_standard_rsi_err_2023-02-19.rda")

data_robust <- rio::import("./markdown/data/diffusion_data_robust.Rdata")
data_classic <- rio::import("./markdown/data/diffusion_data_classic.Rdata")
data_location <- rio::import("./markdown/data/diffusion_data_location.Rdata")

pred_robust <- rio::import("./markdown/models/prediction_robust_standard_2023-02-20.rda")
pred_classic <- rio::import("./markdown/models/prediction_classic_standard_2023-02-20.rda")
pred_location <- rio::import("./markdown/models/prediction_location_standard_2023-02-22.rda")
```

```{r checking rhat}
# Checking parameters with highest rhat
min_ess(fit_wiener_classic)
max_rhat(fit_wiener_classic)

min_ess(fit_wiener_robust)
max_rhat(fit_wiener_robust)

min_ess(fit_wiener_location)
max_rhat(fit_wiener_location)
```

```{r divergent}
# Number of divergent transitions
n_divergent(fit_wiener_classic)
n_divergent(fit_wiener_robust)
n_divergent(fit_wiener_location)
```

```{r visual-par-inspection}
inspect_pars(fit_wiener_classic)
inspect_pars(fit_wiener_robust)
inspect_pars(fit_wiener_location)
```


```{r parameter correlations}
get_max_cors(fit_wiener_classic)
get_max_cors(fit_wiener_robust)
get_max_cors(fit_wiener_location)
```

```{r model-fit}
combine_data <- function(raw_data, prediction){
  combined <- as_tibble(cbind(raw_data, as_tibble(t(prediction))))
  return(combined)
}
combined_data_classic <- combine_data(data_classic, pred_classic)
combined_data_robust <- combine_data(data_robust, pred_robust)
combined_data_location <- combine_data(data_location, pred_location)
```

```{r}
generate_med_rts_pred <- function(combined_data, raw_data, group_id = FALSE){
  if (group_id == FALSE){
    pred_rts = combined_data %>% 
      group_by(rsi, error_factor, stimulus) %>%  # select grouping vars
      summarise_at(.vars = vars(starts_with("V")), 
                   funs(prob.upper = mean(. > 0),
                        medrt.lower = median(abs(.[. < 0]) ),
                        medrt.upper = median(.[. > 0] )
                   )) %>% 
      ungroup() %>% 
      gather("key", "value", -rsi, -error_factor, -stimulus) %>% # remove grouping vars
      separate("key", c("rep", "measure"), sep = "_") %>% 
      spread(measure, value) %>% 
      group_by(rsi, error_factor, stimulus) %>% # select grouping vars
      summarise_at(.vars = vars(prob.upper, medrt.lower, medrt.upper), 
                   funs(median = median(., na.rm = TRUE),
                        llll = quantile(., probs = 0.01,na.rm = TRUE),
                        lll = quantile(., probs = 0.025,na.rm = TRUE),
                        ll = quantile(., probs = 0.1,na.rm = TRUE),
                        l = quantile(., probs = 0.25,na.rm = TRUE),
                        h = quantile(., probs = 0.75,na.rm = TRUE),
                        hh = quantile(., probs = 0.9,na.rm = TRUE),
                        hhh = quantile(., probs = 0.975,na.rm = TRUE),
                        hhhh = quantile(., probs = 0.99,na.rm = TRUE)
                   ))
    total = raw_data %>% 
      group_by(rsi, error_factor, stimulus) %>% # select grouping vars
      summarise(prob.upper = mean(decision == 1),
                medrt.upper = median(rt[decision == 1]),
                medrt.lower = median(rt[decision == 0])
      ) %>% 
      ungroup() %>% 
      left_join(pred_rts)
  } else {
    pred_med = combined_data %>% 
      group_by(id, rsi, error_factor, stimulus) %>%  # select grouping vars
      summarise_at(.vars = vars(starts_with("V")), 
                   funs(prob.upper = mean(. > 0),
                        medrt.lower = median(abs(.[. < 0]) ),
                        medrt.upper = median(.[. > 0] )
                   )) %>% 
      ungroup() %>% 
      gather("key", "value", -id, -rsi, -error_factor, -stimulus) %>% # remove grouping vars
      separate("key", c("rep", "measure"), sep = "_") %>% 
      spread(measure, value) %>% 
      group_by(id, rsi, error_factor, stimulus) %>% # select grouping vars
      summarise_at(.vars = vars(prob.upper, medrt.lower, medrt.upper), 
                   funs(median = median(., na.rm = TRUE),
                        llll = quantile(., probs = 0.01,na.rm = TRUE),
                        lll = quantile(., probs = 0.025,na.rm = TRUE),
                        ll = quantile(., probs = 0.1,na.rm = TRUE),
                        l = quantile(., probs = 0.25,na.rm = TRUE),
                        h = quantile(., probs = 0.75,na.rm = TRUE),
                        hh = quantile(., probs = 0.9,na.rm = TRUE),
                        hhh = quantile(., probs = 0.975,na.rm = TRUE),
                        hhhh = quantile(., probs = 0.99,na.rm = TRUE)
                   ))
    total = raw_data %>% 
      group_by(id, rsi, error_factor, stimulus) %>% # select grouping vars
      summarise(prob.upper = mean(decision == 1),
                medrt.upper = median(rt[decision == 1]),
                medrt.lower = median(rt[decision == 0])
      ) %>% 
      ungroup() %>% 
      left_join(pred_rts)
  }
  return(total)
}

summarize_med_rt <- function(object, group_id = FALSE){
  if (group_id == FALSE){
    summary = object %>% 
      group_by(rsi, error_factor, stimulus) %>% 
      summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
      ungroup()
  } else {
    summary = object %>% 
      group_by(id, rsi, error_factor, stimulus) %>% 
      summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
      ungroup()
  }
}
```

```{r}
robust_med_rts_pred <- generate_med_rts_pred(
  combined_data = combined_data_robust,
  raw_data = data_robust,
  group_id = FALSE
)

robust_summary_pred <- summarize_med_rt(
  robust_med_rts_pred,
  group_id = FALSE
)

classic_med_rts_pred <- generate_med_rts_pred(
  combined_data = combined_data_classic,
  raw_data = data_classic,
  group_id = FALSE
)

classic_summary_pred <- summarize_med_rt(
  classic_med_rts_pred,
  group_id = FALSE
)

location_med_rts_pred <- generate_med_rts_pred(
  combined_data = combined_data_location,
  raw_data = data_location,
  group_id = FALSE
)

location_summary_pred <- summarize_med_rt(
  location_med_rts_pred,
  group_id = FALSE
)


```

```{r}
generate_plot_resp_prob <- function(data){
  labels <- data %>% 
    mutate(labels = paste0(rsi, "_", error_factor, "_", stimulus)) %>% 
    pull(labels)
  labels_upper <- labels[which(str_detect(labels, "_1$"))]
  labels_lower <- labels[which(str_detect(labels, "_0$"))]
  
  plot <- ggplot(data, aes(x = rsi:error_factor:stimulus)) +
    geom_linerange(aes(ymin =  prob.upper_lll, ymax =  prob.upper_hhh), 
                   col = "darkgrey") + 
    geom_linerange(aes(ymin =  prob.upper_ll, ymax =  prob.upper_hh), 
                   size = 2, col = "grey") + 
    geom_point(aes(y = prob.upper_median), shape = 1) +
    geom_point(aes(y = prob.upper), shape = 4, col = "red") +
    ggtitle("Response Probabilities") + 
    ylab("Probability of upper resonse") + xlab("") +
    scale_x_discrete(labels = labels, guide = guide_axis(n.dodge = 2))
  
  return(plot)
}

generate_plot_median_upper <- function(data){
  labels <- data %>% 
    mutate(labels = paste0(rsi, "_", error_factor, "_", stimulus)) %>% 
    pull(labels)
  labels_upper <- labels[which(str_detect(labels, "_1$"))]
  labels_lower <- labels[which(str_detect(labels, "_0$"))]
  
  plot <- ggplot(data %>% filter(stimulus == 1), aes(x = rsi:error_factor)) +
    geom_linerange(aes(ymin =  medrt.upper_lll, ymax =  medrt.upper_hhh), 
                   col = "darkgrey") + 
    geom_linerange(aes(ymin =  medrt.upper_ll, ymax =  medrt.upper_hh), 
                   size = 2, col = "grey") + 
    geom_point(aes(y = medrt.upper_median), shape = 1) +
    geom_point(aes(y = medrt.upper), shape = 4, col = "red") +
    ggtitle("Median RTs upper") + 
    ylab("RT (s)") + xlab("") +
    scale_x_discrete(labels = labels_upper, guide = guide_axis(n.dodge = 2))
  
  return(plot)
}

generate_plot_median_lower <- function(data){
  labels <- data %>% 
    mutate(labels = paste0(rsi, "_", error_factor, "_", stimulus)) %>% 
    pull(labels)
  labels_upper <- labels[which(str_detect(labels, "_1$"))]
  labels_lower <- labels[which(str_detect(labels, "_0$"))]
  
  plot <- ggplot(
    data %>% filter(stimulus == 0),
    aes(x = rsi:error_factor)
    ) +
    geom_linerange(aes(ymin =  medrt.lower_lll, ymax =  medrt.lower_hhh), 
                   col = "darkgrey") + 
    geom_linerange(aes(ymin =  medrt.lower_ll, ymax =  medrt.lower_hh), 
                   size = 2, col = "grey") + 
    geom_point(aes(y = medrt.lower_median), shape = 1) +
    geom_point(aes(y = medrt.lower), shape = 4, col = "red") +
    ggtitle("Median RTs lower") + 
    ylab("RT (s)") + xlab("") +
    scale_x_discrete(labels = labels_lower, guide = guide_axis(n.dodge = 2))
}

combine_all_pred_plots <- function(data){
  p1 <- generate_plot_resp_prob(data)
  p2 <- generate_plot_median_upper(data)
  p3 <- generate_plot_median_lower(data)
  
  grid.arrange(p1, p2, p3, ncol = 2)
}
```

```{r}
combine_all_pred_plots(robust_summary_pred)
combine_all_pred_plots(classic_summary_pred)
combine_all_pred_plots(location_summary_pred)
```

```{r checking full rt distributions}
get_factor_combinations <- function(data){
  factor_combinations <- data %>% 
    mutate(labels = paste0(rsi, "_", error_factor, "_", stimulus)) %>% 
    pull(labels) %>% 
    unique()
  return(factor_combinations)
}

return_vector_of_values <- function(data, my_rsi, my_error_factor, my_stimulus){
  vector <- data %>% 
    filter(rsi == my_rsi, error_factor == my_error_factor, stimulus == my_stimulus) %>% 
    select(starts_with("V")) %>% 
    as.matrix() %>% 
    c() %>% 
    abs()
  return(vector)
}

get_name_quotes <- function(object){
  paste(rlang::get_expr(rlang::enquo(object)))
}

compare_plot <- function(dataframe, vector, my_rsi, my_error_factor, my_stimulus){
  data = dataframe %>% 
    filter(rsi == my_rsi, error_factor == my_error_factor, stimulus == my_stimulus) %>% 
    mutate(type = "empirical") %>% 
    select(rt, type)
  vector_data = data.frame(rt =vector, type = "predicted")
  full_data = rbind(data, vector_data)
  plot = full_data %>%
    ggplot(
      aes(x = rt,
          group = type,
          fill = type)
    )+
    geom_density(alpha = 0.5)+
    labs(
      subtitle = paste0(
        "RSI = ", my_rsi,";", " error_factor = ", my_error_factor,
        "; ", "stimulus = ", my_stimulus
      )
    )+
    theme_classic()+
    xlim(0, 1)
  return(plot)
}

compare_all_conditions <- function(data){
  factor_combinations <- get_factor_combinations(data)
  
  n_factors <- length(factor_combinations)
  grid_width = floor(n_factors/5)
  # generating list of vectors containing all predicted data for those combinations
  list_objects = list()
  list_plots = list()
  for (i in seq_along(factor_combinations)) {
    vec_rsi = str_extract(factor_combinations[i], "^(long|short)")
    vec_error_factor = str_remove(factor_combinations[i], "^(long|short)_") %>% 
      str_remove(., "_(0|1)$")
    vec_stimulus = str_extract(factor_combinations[i], "(0|1)$")
    
    list_objects[[i]] = return_vector_of_values(data = data,
                                              my_rsi = vec_rsi,
                                              my_error_factor = vec_error_factor,
                                              my_stimulus = vec_stimulus)
    list_plots[[i]] = compare_plot(data = data,
                                   vector = list_objects[[i]],
                                 my_rsi = vec_rsi,
                                 my_error_factor = vec_error_factor,
                                 my_stimulus = vec_stimulus)
  }
  
  grid <- grid.arrange(grobs = list_plots, ncol = grid_width)
  return(grid)
}
```

```{r}
robust_visual_fit <- compare_all_conditions(combined_data_robust)
classic_visual_fit <- compare_all_conditions(combined_data_classic)
location_visual_fit <- compare_all_conditions(combined_data_location)
```

