---
editor_options:
  chunk_output_type: console
---
```{r ddm-descriptive-setup}
# Library calls
library(brms)
library(tidyverse)
library(tidybayes)
library(emmeans)
library(loo)
```

```{r ddm-descriptive-functions}
# Custom functions
plot_params <- function(data){
  data %>% 
    ggplot(
      aes(
        x = location,
        y = mean,
        color = type,
        group = type
      )
    )+
    geom_point(size = 2)+
    geom_line()+
    facet_wrap(~rsi)+
    geom_errorbar(
      aes(
        ymin = upper, 
        ymax = lower, 
        width = 0.2
      )
    )+
    geom_vline(
      aes(
        xintercept = 1.5
      ),
      # linetype = "dashed",
      color = "black",
      size = 2,
      alpha = 0.5
    )+
    scale_color_manual(
      values = c("nogo_correct" = "forestgreen",
                 "nogo_error" = "red"),
      name = "NoGo-Accuracy",
      labels = c("Correct", "Error")
    )+
    scale_x_discrete(
      labels = c("-1", "+1", "+2", "+3", "+4", "baseline - Go")
    )+
    labs(
      x = "Location",
      y = "Estimate",
      # caption = "Error bars represent 95% CI"
    )+
    theme_classic()+
    theme(text=element_text(size=20),
          legend.title= element_text(size = 12))
}

plot_post_error <- function(data){
  data %>% 
    filter(type == "nogo_error") %>% 
    ggplot(
      aes(
        x = location,
        y = mean,
        color = rsi,
        group = rsi
      )
    )+
    geom_point(size = 2)+
    geom_line()+
    geom_errorbar(
      aes(
        ymin = upper, 
        ymax = lower, 
        width = 0.2
      )
    )+
    geom_vline(
      aes(
        xintercept = 1.5
      ),
      # linetype = "dashed",
      color = "black",
      size = 2,
      alpha = 0.5
    )+
    scale_x_discrete(
      labels = c("-1", "+1", "+2", "+3", "+4", "baseline - Go")
    )+
    labs(
      x = "Location",
      y = "Estimate",
      # caption = "Error bars represent 95% CI",
      color = ""
    )+
    theme_classic()+
    theme(text=element_text(size=20),
          legend.title = element_text(size = 12))
}

plot_long_rsi <- function(data){
  data %>% 
    filter(rsi == "long RSI") %>% 
    ggplot(
      aes(
        x = location,
        y = mean,
        color = type,
        group = type
      )
    )+
    geom_point(size = 2)+
    geom_line()+
    geom_errorbar(
      aes(
        ymin = upper, 
        ymax = lower, 
        width = 0.2
      )
    )+
    geom_vline(
      aes(
        xintercept = 1.5
      ),
      # linetype = "dashed",
      color = "black",
      size = 2,
      alpha = 0.5
    )+
    scale_color_manual(
      values = c("nogo_correct" = "forestgreen",
                 "nogo_error" = "red"),
      name = "NoGo-Accuracy",
      labels = c("Correct", "Error")
    )+
    scale_x_discrete(
      labels = c("-1", "+1", "+2", "+3", "+4", "baseline - Go")
    )+
    labs(
      x = "Location",
      y = "Estimate",
      # caption = "Error bars represent 95% CI"
    )+
    theme_classic()+
    theme(text=element_text(size=20),
          legend.title= element_text(size = 12))
}
```

```{r ddm-descriptive-data, cache = TRUE}
# Reading in data 
fit <- rio::import("./markdown/diffusion_model_runs/cluster/output/base_model.rda")
fit_robust <- rio::import("./markdown/diffusion_model_runs/cluster/output/base_model_robust.rda")
fit_classic <- rio::import("./markdown/diffusion_model_runs/cluster/output/base_model_classic.rda")
```

```{r ddm-descriptive-counting-location}
location_median_count <- fit$data %>% 
  count(rsi, error_factor) %>% 
  summarize(
    median = median(n),
    sd = sd(n)
  )
```

```{r ddm-descriptive-base-model, cache = TRUE, dependson='ddm-descriptive-data'}
data_location <- fixef(fit) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5)


working_location <- data_location %>% 
  mutate(param = str_replace(param, "previous_stimulus", "prevstim")) %>% 
  mutate(param = str_replace(param, "^rsi", "drift_rsi")) %>% 
  # filter(!str_detect(param, "bias")) %>% 
  separate(param,
           into = c("rsi", "error_factor", "stimulus"),
           sep = ":") %>% 
  # mutate(rsi = ifelse(str_detect(rsi, "^rsi"), paste0("drift_", rsi), rsi)) %>% 
  separate(
    rsi,
    into = c("param", "rsi"),
    sep = "_"
  )
working_location[which(working_location$param == "bias"), c("error_factor", "stimulus")] <- working_location[which(working_location$param == "bias"), c("stimulus", "error_factor")]
 
summary_location <- working_location %>% 
  mutate(
    rsi = str_remove(rsi, "rsi"),
    error_factor = str_remove(error_factor, "error_factor"),
    stimulus = str_remove(stimulus, "stimulus")
  ) %>% 
  mutate(
    error_factor = ifelse(str_detect(error_factor, "baseline"), "C, E", error_factor)
  ) %>% 
  separate_rows(
    error_factor,
    sep = ","
  ) %>% 
  mutate(
    type = ifelse(str_detect(error_factor, "E"), "nogo_error", "nogo_correct")
  ) %>% 
  mutate(
    location = case_when(
      str_detect(error_factor, "M1") ~ -1,
      str_detect(error_factor, "P0") ~ 0,
      str_detect(error_factor, "P1") ~ 1,
      str_detect(error_factor, "P2") ~ 2,
      str_detect(error_factor, "P3") ~ 3,
      str_detect(error_factor, "P4") ~ 4,
      str_detect(error_factor, "C") ~ 5,
      str_detect(error_factor, "E") ~ 5
    )
  ) %>% 
  mutate(mean_corrected = abs(mean), lower_corrected = abs(lower), upper_corrected = abs(upper)) %>% 
  group_by(param, rsi, type, location, stimulus) %>% 
  summarize(
    mean = mean(mean_corrected),
    lower = mean(lower_corrected), 
    upper = mean(upper_corrected)
    ) %>% 
  filter(location != 5) %>% 
  mutate(location = factor(location)) %>% 
  mutate(location = fct_relevel(location, "-1", "1", "2", "3", "4")) %>% 
  mutate(rsi = paste(rsi, "RSI")) %>% 
  mutate(rsi = factor(rsi)) %>% 
  mutate(rsi = fct_relevel(rsi, "short RSI", "long RSI"))



drift_location_rsi_plot <- summary_location %>%
  filter(param == "drift") %>%
  group_by(rsi, location, type) %>%
  summarize(
    mean = mean(mean),
    upper = mean(upper),
    lower = mean(lower)
  ) %>%
  plot_params()

 
drift_location_err_plot <- summary_location %>%
  filter(param == "drift") %>%
  group_by(rsi, location, type) %>%
  summarize(
    mean = mean(mean),
    upper = mean(upper),
    lower = mean(lower)
  ) %>%
  plot_post_error()

drift_location_long_rsi <- summary_location %>% 
  filter(param == "drift") %>% 
  group_by(rsi, location, type) %>%
  summarize(
    mean = mean(mean),
    upper = mean(upper),
    lower = mean(lower)
  ) %>%
  plot_long_rsi()

bs_location_rsi_plot <- summary_location %>%
  filter(param == "bs") %>%
  plot_params()

bs_location_err_plot <- summary_location %>%
  filter(param == "bs") %>%
  plot_post_error()

bs_location_long_rsi <- summary_location %>% 
  filter(param == "bs") %>% 
  plot_long_rsi()

ndt_location_rsi_plot <- summary_location %>%
  filter(param == "ndt") %>%
  plot_params()

ndt_location_err_plot <- summary_location %>%
  filter(param == "ndt") %>%
  plot_post_error()

ndt_location_long_rsi <- summary_location %>% 
  filter(param == "ndt") %>% 
  plot_long_rsi()

bias_location_rsi_plot <- summary_location %>%
  filter(param == "bias") %>%
  mutate(
    lower_copy = lower,
    upper_copy = upper,
    mean = ifelse(
      stimulus == "prevstimX",
      1 - mean,
      mean
    ),
    upper = ifelse(
      stimulus == "prevstimX",
      1 - lower_copy, # need to turn this around for inversion
      upper
    ),
    lower = ifelse(
      stimulus == "prevstimX",
      1 - upper_copy,
      lower
    )
  ) %>%
  select(-ends_with("copy")) %>%
  group_by(location, rsi, type) %>%
  summarize(mean = mean(mean),
            upper = mean(upper),
            lower = mean(lower))  %>%
  plot_params()

bias_location_err_plot <- summary_location %>%
  filter(param == "bias") %>%
  mutate(
    lower_copy = lower,
    upper_copy = upper,
    mean = ifelse(
      stimulus == "prevstimX",
      1 - mean,
      mean
    ),
    upper = ifelse(
      stimulus == "prevstimX",
      1 - lower_copy, # need to turn this around for inversion
      upper
    ),
    lower = ifelse(
      stimulus == "prevstimX",
      1 - upper_copy,
      lower
    )
  ) %>%
  select(-ends_with("copy")) %>%
  group_by(location, rsi, type) %>%
  summarize(mean = mean(mean),
            upper = mean(upper),
            lower = mean(lower))  %>%
  plot_post_error()

bias_location_long_rsi <- summary_location %>%
  filter(param == "bias") %>%
  mutate(
    lower_copy = lower,
    upper_copy = upper,
    mean = ifelse(
      stimulus == "prevstimX",
      1 - mean,
      mean
    ),
    upper = ifelse(
      stimulus == "prevstimX",
      1 - lower_copy, # need to turn this around for inversion
      upper
    ),
    lower = ifelse(
      stimulus == "prevstimX",
      1 - upper_copy,
      lower
    )
  ) %>%
  select(-ends_with("copy")) %>%
  group_by(location, rsi, type) %>%
  summarize(mean = mean(mean),
            upper = mean(upper),
            lower = mean(lower))  %>%
  plot_long_rsi()
```

```{r ddm-descriptive-robust, cache = TRUE, eval = FALSE}
data_robust <- fixef(fit_robust) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5)


working_robust <- data_robust %>% 
  mutate(param = str_replace(param, "previous_stimulus", "prevstim")) %>% 
  mutate(param = str_replace(param, "^rsi", "drift_rsi")) %>% 
  # filter(!str_detect(param, "bias")) %>% 
  separate(param,
           into = c("rsi", "error_factor", "stimulus"),
           sep = ":") %>% 
  # mutate(rsi = ifelse(str_detect(rsi, "^rsi"), paste0("drift_", rsi), rsi)) %>% 
  separate(
    rsi,
    into = c("param", "rsi"),
    sep = "_"
  )
working_robust[which(working_robust$param == "bias"), c("error_factor", "stimulus")] <- working_robust[which(working_robust$param == "bias"), c("stimulus", "error_factor")]
 
summary_robust <- working_robust %>% 
  mutate(
    rsi = str_remove(rsi, "rsi"),
    error_factor = str_remove(error_factor, "error_factor"),
    stimulus = str_remove(stimulus, "stimulus")
  ) %>% 
  mutate(
    error_factor = ifelse(str_detect(error_factor, "baseline"), "C, E", error_factor)
  ) %>% 
  separate_rows(
    error_factor,
    sep = ","
  ) %>% 
  mutate(
    type = ifelse(str_detect(error_factor, "E"), "nogo_error", "nogo_correct")
  ) %>% 
  mutate(
    location = case_when(
      str_detect(error_factor, "M1") ~ -1,
      str_detect(error_factor, "P0") ~ 0,
      str_detect(error_factor, "P1") ~ 1,
      str_detect(error_factor, "P2") ~ 2,
      str_detect(error_factor, "P3") ~ 3,
      str_detect(error_factor, "P4") ~ 4,
      str_detect(error_factor, "C") ~ 5,
      str_detect(error_factor, "E") ~ 5
    )
  ) %>% 
  mutate(mean_corrected = abs(mean), lower_corrected = abs(lower), upper_corrected = abs(upper)) %>% 
  group_by(param, rsi, type, location, stimulus) %>% 
  summarize(
    mean = mean(mean_corrected),
    lower = mean(lower_corrected), 
    upper = mean(upper_corrected)
    ) %>% 
  filter(location != 5)
```

```{r ddm-descriptive-classic, cache = TRUE, eval = FALSE}
data_classic <- fixef(fit_classic) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  select(param = rowname,
         mean = Estimate,
         error = `Est.Error`,
         lower = Q2.5,
         upper = Q97.5)


working_classic <- data_classic %>% 
  mutate(param = str_replace(param, "previous_stimulus", "prevstim")) %>% 
  mutate(param = str_replace(param, "^rsi", "drift_rsi")) %>% 
  # filter(!str_detect(param, "bias")) %>% 
  separate(param,
           into = c("rsi", "error_factor", "stimulus"),
           sep = ":") %>% 
  # mutate(rsi = ifelse(str_detect(rsi, "^rsi"), paste0("drift_", rsi), rsi)) %>% 
  separate(
    rsi,
    into = c("param", "rsi"),
    sep = "_"
  )
working_classic[which(working_classic$param == "bias"), c("error_factor", "stimulus")] <- working_classic[which(working_classic$param == "bias"), c("stimulus", "error_factor")]
 
summary_classic <- working_classic %>% 
  mutate(
    rsi = str_remove(rsi, "rsi"),
    error_factor = str_remove(error_factor, "error_factor"),
    stimulus = str_remove(stimulus, "stimulus")
  ) %>% 
  mutate(
    error_factor = ifelse(str_detect(error_factor, "baseline"), "C, E", error_factor)
  ) %>% 
  separate_rows(
    error_factor,
    sep = ","
  ) %>% 
  mutate(
    type = ifelse(str_detect(error_factor, "E"), "nogo_error", "nogo_correct")
  ) %>% 
  mutate(
    location = case_when(
      str_detect(error_factor, "M1") ~ -1,
      str_detect(error_factor, "P0") ~ 0,
      str_detect(error_factor, "P1") ~ 1,
      str_detect(error_factor, "P2") ~ 2,
      str_detect(error_factor, "P3") ~ 3,
      str_detect(error_factor, "P4") ~ 4,
      str_detect(error_factor, "C") ~ 5,
      str_detect(error_factor, "E") ~ 5
    )
  ) %>% 
  mutate(mean_corrected = abs(mean), lower_corrected = abs(lower), upper_corrected = abs(upper)) %>% 
  group_by(param, rsi, type, location, stimulus) %>% 
  summarize(
    mean = mean(mean_corrected),
    lower = mean(lower_corrected), 
    upper = mean(upper_corrected)
    ) %>% 
  filter(location != 5)
```

