# Behavioral
```{r appendix-tab-robust-desc}
table_overview_robust %>% 
  mutate_if(is.numeric, ~round(., 2)) %>% 
  mutate(rt = paste0(rt_mean, " (", rt_sd, ")"),
         acc = paste0(acc_mean, " (", acc_sd, ")")) %>% 
  mutate(omission_rate = paste0(omission_rate*100, "%")) %>% 
  select(RSI = rsi, type = error_code, RT = rt, ACC = acc, `omission rate` = omission_rate) %>% 
  mutate(type = str_replace(type, "_", "-")) %>% 
  as.data.frame() %>% 
  apa_table(
    caption = "Descriptive Statistics - Robust Approach",
    note = "Descriptive statistics for post-error effects classified using the robust approach. RSI = Response stimulus interval, RT = response time, ACC = accuracy. RT is measured in ms. Accuracy represents the mean accuracy when a response is given. Omission rate represents the percentage of trials in which no response is given. Type represents the classification of the trial depending on the accuracy of the following or previous trial. Standard deviations are printed in parentheses following mean values.", 
    placement = "h"
  )
  
```
```{r appendix-tab-classic-desc}
table_overview_classic %>% 
  mutate_if(is.numeric, ~round(., 2)) %>% 
  mutate(rt = paste0(rt_mean, " (", rt_sd, ")"),
         acc = paste0(acc_mean, " (", acc_sd, ")")) %>% 
  mutate(omission_rate = paste0(omission_rate*100, "%")) %>% 
  select(RSI = rsi, type = classic_pes_type, RT = rt, ACC = acc, `omission rate` = omission_rate) %>% 
  mutate(type = str_replace(type, "_", "-")) %>% 
  as.data.frame() %>% 
  apa_table(
    caption = "Descriptive Statistics - Classical Approach",
    note = "Descriptive statistics for post-error effects classified using the classical approach. RSI = Response stimulus interval, RT = response time, ACC = accuracy. RT is measured in ms. Accuracy represents the mean accuracy when a response is given. Omission rate represents the percentage of trials in which no response is given. Type represents the classification of the trial depending on the accuracy of the following or previous trial. Standard deviations are printed in parentheses following mean values.",
    placement = "h"
  )
  
```


# Model comparison
```{r appendix-rsi-compare}
rsi_comp %>% 
  as.data.frame() %>% 
  mutate(model = rownames(.)) %>% 
  select(model, elpd_loo, elpd_diff, se_diff) %>% 
  remove_rownames() %>% 
  apa_table(caption = "Model comparison",
            note = "The base model allows all parameters to be influenced by both factors RSI and error-condition. The 'no_rsi_model' allows none of the parameters to be influenced by RSI. The other four models allow all other parameters but the parameter listed in the name to vary between RSI",
            placement = "h")
```

```{r appendix-err-compare}
err_comp %>% 
  as.data.frame() %>% 
  mutate(model = rownames(.)) %>% 
  select(model, elpd_loo, elpd_diff, se_diff) %>% 
  remove_rownames() %>% 
  apa_table(caption = "Model comparison",
            note = "The base model allows all parameters to be influenced by both factors RSI and error-condition. The 'no_error_factor_model' allows none of the parameters to be influenced by error-condition. The other four models allow all other parameters but the parameter listed in the name to vary between error-conditions")
```

```{r appendix-only-compare}
only_comp %>% 
  as.data.frame() %>% 
  mutate(model = rownames(.)) %>% 
  select(model, elpd_loo, elpd_diff, se_diff) %>% 
  remove_rownames() %>% 
  apa_table(caption = "Model comparison",
            note = "The base model allows all parameters to be influenced by both factors RSI and error-condition. The 'no_error_factor_model' allows none of the parameters to be influenced by error-condition. The other four models only allow the parameter listed in the name to vary between error-conditions")
```

