---
editor_options:
  chunk_output_type: console
---
<!-- # Library calls -->
```{r data-prep-setup}
library(tidyverse)
library(rio)
library(data.table)
```

```{r data-prep-functions}

```

<!-- # Reading in data -->
```{r data-prep-importing-data, cache = TRUE, cache.extra = tools::md5sum(list.files("./markdown/data", pattern = ".csv", full.names = TRUE))}
# For auto-read
path <- "./markdown/data/"
keyword <- "bat_bachelor"

data <- list.files(
  path = path,
  pattern = keyword,
  full.names = T
  ) %>%
  map(data.table::fread) %>% 
  data.table::rbindlist(
    fill = TRUE
  ) %>% 
  janitor::clean_names() %>% # make all names snake_case
  mutate(key_resp_trial_rt = ifelse(participant %in% 1:3, # added a 0.1 dead time after first three participants
                                    key_resp_trial_rt,
                                    key_resp_trial_rt + 0.1)) %>% 
  rename(
    "id" = participant,
    "block" = loop_exp_this_n,
    "trial" = loop_trials_this_n,
    "response" = key_resp_trial_keys,
    "acc" = key_resp_trial_corr,
    "rt" = key_resp_trial_rt
  )

```

```{r data-prep-checking condition mappings}
condition_table <- data %>% 
  count(map_condition, map_x_key, map_y_key) %>% 
  filter(!is.na(map_condition))
```

```{r data-prep-extracting demo data}
demo_data <- data %>% 
  select(id, alter, geschlecht_w_m_d_andere, studiengang) %>% 
  unique() %>% 
  mutate(id = as.numeric(id)) %>% 
  arrange(id) %>% 
  mutate( # data from logbuch.xlsx
    geschlecht_w_m_d_andere = ifelse(
      id %in% 1:7,
      "w",
      geschlecht_w_m_d_andere
    ),
    studiengang = ifelse(
      id %in% c(1:3, 5:7),
      "Psychologie",
      studiengang
    )
  )

# From logbuch_ba
demo_data[1:7, "alter"] <- c(20, 19, 21, 19, 23, 20, 21)
demo_data[4, "studiengang"] <- "Bildungswissenschaften, Nebenfach Psychologie"
demo_data <- demo_data %>% 
  filter(!is.na(id))
# No demo data was collected for first 7 participants (have in logbuch_ba.xlsx)
```

<!-- # Filtering out practice trials -->
```{r data-prep-sort exp trials, cache = TRUE, dependson='data-prep-importing-data'}
exp_data <- data %>% 
  group_by(id) %>% # want to have map_x_key and map_y_key everywhere
  mutate(
    map_x_key = ifelse(map_x_key == "", NA, map_x_key),
    map_y_key = ifelse(map_y_key == "", NA, map_y_key)
  ) %>% 
  fill(map_x_key, .direction = "down") %>% 
  fill(map_y_key, .direction = "down") %>% 
  fill(map_condition, .direction = "down") %>% 
  ungroup() %>% 
  filter(is.na(loop_practice_this_n)) %>%  # Filter all practice trials
  janitor::remove_empty(which = "cols") # remove all columns that have just NA, could also remove all empty rows aswell

exp_data <- exp_data %>% # selecting important variables to front
  select(id, block, trial, trial_type, acc, rt,
         response, map_condition,
         everything())
```

```{r data-prep-adding decision variable, cache = TRUE, dependson='data-prep-importing-data'}
dec_data <- exp_data %>% 
  mutate(decision_char = case_when(
    map_condition == 0 & response == "l" ~ "y",
    map_condition == 0 & response == "d" ~ "x",
    map_condition == 1 & response == "l" ~ "x",
    map_condition == 1 & response == "d" ~ "y",
    response == "None" ~ "none"
  )) %>% 
  mutate(decision = case_when(
    decision_char == "x" ~ 0,
    decision_char == "y" ~ 1,
    decision_char == "none" ~ -9
  ))
```

```{r data-prep-just experimental data}
rt_data <- dec_data %>% 
  filter(!is.na(block)) # n.obs should be multiple of 3000
```

```{r data-prep-adding-prev-trial}
trial_data <- rt_data %>% 
  group_by(id, block) %>% 
  mutate(
    previous_stimulus = lag(stimulus),
    previous_trial_type = lag(trial_type),
    previous_acc = lag(acc)
  )
```

```{r data-prep-prepare-coding-error-type, cache = TRUE}
lagged_data <- trial_data %>% 
  group_by(id, block) %>% 
  mutate(
    lag_trial_type_1 = lag(trial_type, 1),
    lead_trial_type_1 = lead(trial_type, 1),
    lag_acc_1 = lag(acc, 1),
    lead_acc_1 = lead(acc, 1),
    lag_rt_1 = lag(rt, 1),
    lead_rt_1 = lead(rt, 1),
    
    lag_trial_type_2 = lag(trial_type, 2),
    lead_trial_type_2 = lead(trial_type, 2),
    lag_acc_2 = lag(acc, 2),
    lead_acc_2 = lead(acc, 2),
    lag_rt_2 = lag(rt, 2),
    lead_rt_2 = lead(rt, 2),
    
    lag_trial_type_3 = lag(trial_type, 3),
    lead_trial_type_3 = lead(trial_type, 3),
    lag_acc_3 = lag(acc, 3),
    lead_acc_3 = lead(acc, 3),
    lag_rt_3 = lag(rt, 3),
    lead_rt_3 = lead(rt, 3),
    
    lag_trial_type_4 = lag(trial_type, 4),
    lead_trial_type_4 = lead(trial_type, 4),
    lag_acc_4 = lag(acc, 4),
    lead_acc_4 = lead(acc, 4),
    lag_rt_4 = lag(rt, 4),
    lead_rt_4 = lead(rt, 4),
  ) %>% 
  ungroup()
```

```{r data-prep-coding-error-robust, cache = TRUE, warning = FALSE, dependson='data-prep-importing-data'}
# just coding errors in nogo trials as error
error_robust_data <- lagged_data %>% 
  mutate(
    error_type = case_when(
      trial_type == "nogo" & acc == 0 & lag_trial_type_1 == "go" & lead_trial_type_1 =="go" ~ "error_single_lure",
      trial_type == "nogo" & acc == 0 & lag_trial_type_1 == "go" & lead_trial_type_1 == "nogo" ~ "error_double_lure_first",
      trial_type == "nogo" & acc == 0 & lag_trial_type_1 == "nogo" & lead_trial_type_1 == "go" ~ "error_double_lure_second",
    )
  ) %>% 
  mutate(
    error_code = case_when(
      lead(error_type) == "error_single_lure" ~ -1,
      error_type == "error_single_lure" ~ 0,
      lag(error_type) == "error_single_lure" ~ 1
    )
  ) %>% 
  ungroup()
```


```{r data-prep-coding-error-classic, cache = TRUE, warning = FALSE, dependson='data-prep-importing-data'}
error_classic_data <- error_robust_data %>% 
  # group_by(id, block) %>% 
  mutate(classic_pes_type = case_when( # for classic, can do double nogo aswell
    lag_trial_type_1 == "nogo" & trial_type == "go" & lag_acc_1 == 0 ~ "post_error",
    !is.na(lag_rt_1) & lag_acc_1 == 1 & trial_type == "go" ~ "post_correct"
  )) %>% 
  ungroup()
```


```{r data-prep-coding-error-location, cache = TRUE, warning = FALSE, dependson='data-prep-importing-data'}
error_location_data <- error_classic_data %>% 
  mutate(
    location = case_when(
      trial_type == "go" & lead_trial_type_1 == "nogo" & lead_acc_1 == 1 
      & !is.na(lag_rt_1) ~ "C-1",
      trial_type == "go" & lead_trial_type_1 == "nogo" & lead_acc_1 == 0 
      & !is.na(lag_rt_1) ~ "E-1",
      trial_type == "nogo" & acc == 1 ~ "C",
      trial_type == "nogo" & acc == 0 ~ "E",
      trial_type == "go" & lag_trial_type_1 == "nogo" & lag_acc_1 == 0 ~ "E+1",
      trial_type == "go" & lag_trial_type_1 == "nogo" & lag_acc_1 == 1 ~ "C+1",
      # For +2 Location I am not always mutually exclusive, so extra precaution needed
      trial_type == "go" & lag_trial_type_1 == "go" 
      & lag_trial_type_2 == "nogo" & lag_acc_2 == 0 
      & !is.na(lag_rt_1) # dont want responses after no-responses in here
      & lead_trial_type_1 != "nogo" ~ "E+2",
      trial_type == "go" & lag_trial_type_1 == "go" 
      & lag_trial_type_2 == "nogo" & lag_acc_2 == 1
      & !is.na(lag_rt_1)
      & lead_trial_type_1 != "nogo" ~ "C+2",
      trial_type == "go" & lag_trial_type_1 == "go" & lag_trial_type_2 == "go"
      & lag_trial_type_3 == "nogo" & lag_acc_3 == 0 
      & !is.na(lag_rt_1) # dont want responses after no-responses in here
      & lead_trial_type_1 != "nogo" ~ "E+3",
      trial_type == "go" & lag_trial_type_1 == "go" & lag_trial_type_2 == "go"
      & lag_trial_type_3 == "nogo" & lag_acc_3 == 1 
      & !is.na(lag_rt_1) # dont want responses after no-responses in here
      & lead_trial_type_1 != "nogo" ~ "C+3",
      trial_type == "go" & lag_trial_type_1 == "go" & lag_trial_type_2 == "go"
      & lag_trial_type_3 == "go"
      & lag_trial_type_4 == "nogo" & lag_acc_4 == 0 
      & !is.na(lag_rt_1) # dont want responses after no-responses in here
      & lead_trial_type_1 != "nogo" ~ "E+4",
      trial_type == "go" & lag_trial_type_1 == "go" & lag_trial_type_2 == "go"
      & lag_trial_type_3 == "go"
      & lag_trial_type_4 == "nogo" & lag_acc_4 == 1
      & !is.na(lag_rt_1) # dont want responses after no-responses in here
      & lead_trial_type_1 != "nogo" ~ "C+4",
    )
  ) %>% 
  mutate(
    location = ifelse(is.na(location) & trial_type == "go", "baseline", location)
  ) %>%
  ungroup() %>% 
  mutate(
    nogo_type = ifelse(location == "baseline", "baseline", str_extract(location, "^E|C")),
    distance = ifelse(location == "baseline", 9, parse_number(location))
  )
```

```{r data-prep-error id, cache = TRUE, dependson='data-prep-importing-data'}
speed_data <- error_location_data %>% 
  group_by(id, block) %>% 
  mutate(
    error_id = case_when(
      error_code == 0 ~ paste(id, block, trial, sep = "_"),
      error_code == -1 ~ paste(id, block, trial + 1, sep = "_"),
      error_code == 1 ~ paste(id, block, trial - 1, sep = "_")
    )
  ) %>% 
  ungroup() %>% 
  group_by(id) %>% 
  mutate(error_speed = case_when(
    error_code == 0 &
      rt >= median(rt, na.rm = TRUE) ~ "slow",
    error_code == 0 &
      rt < median(rt, na.rm = TRUE) ~ "fast"
  )) %>% 
  mutate(error_speed = case_when(
    error_id == lag(error_id) & error_id == lag(error_id, 2) ~ lag(error_speed),
    error_id == lead(error_id) & error_id == lead(error_id, 2) ~ lead(error_speed),
    error_id == error_id ~ error_speed
  )) %>% 
  ungroup()
```

```{r data-prep-filtering participants, cache = TRUE, dependson='data-prep-importing-data'}
# Filter out too fast responses aswell as 
outliers <- speed_data %>% 
  filter(rt > 0.15 | is.na(rt)) %>% 
  # filter(block > 1 | (block <= 1 & trial > 10)) %>% 
  group_by(id, rsi, trial_type) %>% 
  summarize(mean_rt = mean(log(rt), na.rm = TRUE),
            mean_acc = mean(acc, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(rsi, trial_type) %>% 
  mutate(outlier = ifelse(
    mean_rt > mean(mean_rt) + 3*sd(mean_rt) |
      mean_rt < mean(mean_rt) - 3*sd(mean_rt) |
      mean_acc > mean(mean_acc) + 3*sd(mean_acc) |
      mean_acc < mean(mean_acc) - 3*sd(mean_acc),
    1,
    0
  )) %>% 
  select(id, outlier, rsi, mean_rt, mean_acc) %>% 
  filter(outlier == 1) %>% 
  ungroup()

n_outliers <- nrow(outliers %>% distinct(id))

# Don't exclude within participants
outlier_data <- speed_data %>% 
  filter(!id %in% outliers$id) %>% 
  # filter(block > 1 | (block <= 1 & trial > 10)) %>% 
  filter(rt > 0.15 | is.na(rt))

final_data <- outlier_data %>% mutate(rt = rt*1000, rt_s = rt)

```

```{r data-prep-append-demo, cache = TRUE, dependson='data-prep-importing-data'}
demo_output <- demo_data %>% 
  mutate(is_psych = ifelse(
    str_detect(tolower(studiengang), "psych") | str_detect(tolower(studiengang), "bildung"),
    1,
    0
  )) %>% 
  mutate(geschlecht_w_m_d_andere = ifelse( # dealing with "weiblich" / "männlich"
    str_detect(tolower(geschlecht_w_m_d_andere), "w"),
    "w",
    geschlecht_w_m_d_andere
  )) %>% 
  mutate(is_women = ifelse(
    geschlecht_w_m_d_andere == "w",
    1,
    0
    )) %>% 
  # mutate(alter = readr::parse_number(alter)) %>% 
  summarize(
    n_subjects = length(unique(id)),
    n_women = sum(is_women, na.rm = TRUE),
    n_psych = sum(is_psych, na.rm = TRUE),
    gender_perc = sum(is_women, na.rm = TRUE) / sum(!is.na(is_women)),
    mean_age = mean(alter, na.rm = TRUE),
    max_age = max(alter, na.rm = TRUE),
    min_age = min(alter, na.rm = TRUE),
    sd_age = sd(alter, na.rm = TRUE),
    psych_perc = sum(is_psych, na.rm = TRUE) / sum(!is.na(is_psych)),
    na_gender = sum(is.na(geschlecht_w_m_d_andere)),
    na_psych = sum(is.na(studiengang)),
    na_alter = sum(is.na(alter))
  ) %>% 
  mutate(n_outliers = n_outliers)

```

```{r data-prep-lost trials}
trials_lost_filter <- nrow(rt_data) - nrow(final_data) - 3000 * n_outliers # lose 3000 trials per outlier
percentage_trials_lost <- round(trials_lost_filter / nrow(rt_data), 4)*100

demo_output$percentage_trials_lost <- percentage_trials_lost
```


```{r data-prep-saving data}
export(final_data, "./markdown/data/analysis_data.Rdata")
export(demo_output, "./markdown/data/demo_output.rdata")
```

