---
editor_options:
  chunk_output_type: console
---
<!-- # Library calls -->
```{r descriptive-analysis-setup}
library(tidyverse)
library(rio)
library(data.table)
library(scales)

ggplot2::theme_set(theme_classic()) # setting default theme
```

```{r descriptive-analysis-functions}

```

```{r descriptive-analysis-data, cache = TRUE, cache.extra = tools::md5sum("./markdown/data/analysis_data.Rdata")}
data <- rio::import("./markdown/data/analysis_data.Rdata")
```

```{r descriptive-analysis-descriptive data}
mean_error_rate_overall <- (1 - mean(data$acc, na.rm = TRUE)) * 100

mean_error_rate_nogo <- data %>% 
  filter(trial_type == "nogo") %>% 
  summarise(mean_acc = mean(acc, na.rm = TRUE))

mean_error_rate_nogo <- (1 - mean_error_rate_nogo$mean_acc)*100

mean_rt <- mean(data$rt, na.rm = TRUE)

mean_rt_short <- data %>% 
  filter(rsi == 0.2) %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE)) %>% .$mean_rt

mean_rt_long <- data %>% 
  filter(rsi == 1) %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE)) %>% .$mean_rt

mean_rt_go <- data %>% 
  filter(trial_type == "go") %>% 
  summarize(mean_rt = mean(rt, na.rm = TRUE)) %>% .$mean_rt

# Want to do descriptives with classic pes. robust makes no sense with go-nogotask
mean_rt_post_correct <- data %>% 
  filter(classic_pes_type == "post_correct") %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE)) %>% .$mean_rt

mean_rt_post_error <- data %>% 
  filter(classic_pes_type == "post_error") %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE)) %>% .$mean_rt

mean_acc_post_correct <- data %>% 
  filter(classic_pes_type == "post_correct") %>% 
  summarise(mean_acc = mean(acc, na.rm = TRUE)) %>% .$mean_acc

mean_acc_post_error <- data %>% 
  filter(classic_pes_type == "post_error") %>% 
  summarise(mean_acc = mean(acc, na.rm = TRUE)) %>% .$mean_acc

mean_acc_error_rsi_comp <- data %>%
  group_by(rsi, classic_pes_type) %>% 
  summarise(mean_acc = mean(acc, na.rm = TRUE))

mean_rt_error_rsi_comp <- data %>% 
  group_by(rsi, classic_pes_type) %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE))

# TODO: Create dataframe containing descriptive mean rts and accs for different conditions
# Want mean rt on 

average_n_nogo_error <- data %>% 
  group_by(id, trial_type) %>% 
  count(classic_pes_type) %>% 
  filter(!is.na(classic_pes_type)) %>% 
  group_by(classic_pes_type) %>% 
  summarize(mean = mean(n), sd = sd(n), median = median(n))
  
average_n_nogo_error_robust <- data %>% 
  group_by(id, trial_type) %>% 
  count(error_code) %>% 
  filter(!is.na(error_code)) %>% 
  group_by(error_code) %>%
  summarize(mean = mean(n), sd = sd(n), median = median(n))

    descriptive_output <- data.frame(
  mean_error_rate_overall,
  mean_error_rate_nogo,
  mean_rt,
  mean_rt_go,
  mean_rt_short,
  mean_rt_long,
  mean_rt_post_correct,
  mean_rt_post_error,
  mean_acc_post_correct,
  mean_acc_post_error
)
```

```{r descriptive-analysis-classic pes, include = FALSE, eval = FALSE}
# Maybe we'd wanna run this, to compare trials on equal footing
# nonetheless, a "correct" response means waiting longer, leading to different rt then after an error response
data %>% 
  group_by(rsi, classic_pes_type) %>% 
  summarize(mean_rt = mean(rt, na.rm = TRUE), 
            count = n())

data %>% 
  group_by(id, rsi) %>% 
  count(classic_pes_type) %>% 
  filter(classic_pes_type == "post_error",
         n < 50)
```

```{r descriptive-analysis-block comparison, include = FALSE, cache = TRUE, dependson='descriptive-analysis-data', eval = FALSE}
data %>% 
  group_by(rsi, block) %>% 
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarize(mean_rt = mean(rt, na.rm = TRUE),
            mean_acc = mean(acc, na.rm = TRUE),
            count = n()) %>% 
  ggplot(aes(
    x = block,
    y = mean_rt,
    group = rsi,
    color = factor(rsi)
  ))+
  geom_line()

data %>% 
  mutate(block_fifths = case_when(
    trial < 50 ~ block + 0.2,
    trial < 100 ~ block + 0.4,
    trial < 150 ~ block + 0.6,
    trial < 200 ~ block + 0.8,
    trial < 250 ~ block + 1
  )) %>%
  group_by(rsi, block_fifths) %>%
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>%
  summarize(mean_rt = mean(rt, na.rm = TRUE),
            mean_acc = mean(acc, na.rm = TRUE),
            count = n()) %>% 
  ggplot(aes(
    x = block_fifths,
    y = mean_acc,
    group = rsi,
    color = factor(rsi)
  ))+
  geom_line()
# Check whether accuracy difference overall in RSI is driven by go trials
data %>% 
  group_by(rsi, trial_type, block) %>% 
  summarise(mean_rt = mean(rt, na.rm = TRUE),
            mean_acc = sum(acc)/n(),
            count = n())
```

```{r descriptive-analysis-visualization, include = FALSE, cache = TRUE, dependson='descriptive-analysis-data'}
data %>% 
  group_by(rsi, error_code) %>% 
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarise(
    mean_rt = mean(rt, na.rm = TRUE),
    sd_rt = sd(rt, na.rm = TRUE),
    mean_acc = mean(acc, na.rm = TRUE),
    sd_acc = sd(acc, na.rm = TRUE)
  ) %>% 
  mutate(error_code = ifelse(is.na(error_code), "other", error_code)) %>% 
  ggplot(aes(
    x = error_code, 
    y = mean_rt,
    group = rsi,
    color = factor(rsi)
  )) +
  geom_line()

data %>% 
  group_by(rsi, error_code) %>% 
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarise(
    mean_rt = mean(rt, na.rm = TRUE),
    sd_rt = sd(rt, na.rm = TRUE),
    mean_acc = mean(acc, na.rm = TRUE),
    sd_acc = sd(acc, na.rm = TRUE)
  ) %>% 
  mutate(error_code = ifelse(is.na(error_code), "other", error_code)) %>% 
  filter(error_code %in% c(-1, 1, "other")) %>% 
  ggplot(aes(
    x = error_code,
    y = mean_acc,
    group = rsi,
    color = factor(rsi)
  )) +
  geom_line()

plot_rt_pes <- data %>% 
  group_by(rsi, classic_pes_type) %>% 
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarise(
    across(
      c("rt", "acc"),
      list(sd = ~sd(., na.rm = TRUE), mean = ~mean(., na.rm = TRUE))
      )
    ) %>% 
  mutate(classic_pes_type = ifelse(is.na(classic_pes_type), "other", classic_pes_type)) %>% 
  filter(classic_pes_type != "other") %>% 
  ggplot(
    aes(
      x = factor(rsi),
      y = rt_mean,
      group = classic_pes_type,
      fill = classic_pes_type
    )
  ) +
  geom_bar(stat = "identity", position = "dodge")+
  labs(
    title = "Mean Reaction Times",
    x = "Response Stimulus Interval (s)",
    y = "Mean Reaction Time (s)",
    fill = ""
  )

plot_acc_pes <- data %>% 
  group_by(rsi, classic_pes_type) %>% 
  # filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarise(
    across(
      c("rt", "acc"),
      list(sd = ~sd(., na.rm = TRUE), mean = ~mean(., na.rm = TRUE))
      )
    ) %>% 
  mutate(classic_pes_type = ifelse(is.na(classic_pes_type), "other", classic_pes_type)) %>% 
  filter(classic_pes_type != "other") %>% 
  ggplot(
    aes(
      x = factor(rsi),
      y = acc_mean,
      group = classic_pes_type,
      fill = classic_pes_type
    )
  ) +
  geom_bar(stat = "identity", position = "dodge")+
  labs(
    title = "Mean Accuracy",
    x = "Response Stimulus Interval (s)",
    y = "Mean Accuracy",
    fill = ""
  )+
  scale_y_continuous(labels = label_percent())
```

<!-- # TODO: Something about "fast" vs. "slow" errors -->
```{r descriptive-analysis-error rate without noresponse, include = FALSE, eval = FALSE}
data %>% 
  group_by(rsi, error_code) %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  summarize(
    across(
      c("rt", "acc"),
      list(mean = ~mean(., na.rm = TRUE)) 
    )
  )
```


```{r descriptive-analysis-fast slow error, include = FALSE, eval = FALSE}
data %>% 
  filter(!is.na(error_speed)) %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  group_by(rsi, error_speed, error_code) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE)
      )
    )
  )
```


```{r descriptive-analysis-condition comparison, include = FALSE, eval = FALSE}
data %>% 
  group_by(rsi, map_condition) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  )

```

```{r descriptive-analysis-exporting, include = FALSE}
rio::export(descriptive_output, "./markdown/data/descriptive_output.rdata")
# ggsave(plot_rt_pes, file = "./markdown/images/plot_rt_pes.jpg")
# ggsave(plot_acc_pes, file = "./markdown/images/plot_acc_pes.jpg")
```

```{r descriptive-analysis-overview-table, include = FALSE, cache = TRUE, dependson='descriptive-analysis-data'}
# get table of mean rt and acc: overall, in go/nogo in short/long in C+1/E+1
# put SD in there too
# Refactor Location level
descriptive_analysis_overview_table <- data %>% 
  # filter(!is.na(rt)) %>% 
  group_by(rsi, trial_type, location) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  mutate(count = acc_count) %>% 
  select(-c("rt_count", "acc_count")) %>% 
  mutate(
    rt_mean = papaja::apa_num(rt_mean),
    rt_sd = papaja::apa_num(rt_sd),
    rt = paste0(rt_mean, " (", rt_sd, ")")
    ) %>% 
  mutate(
    acc_mean = papaja::apa_num(acc_mean, gt1 = FALSE),
    acc_sd = papaja::apa_num(acc_sd, gt1 = FALSE),
    acc = paste0(acc_mean, " (", acc_sd, ")")
    ) %>% 
  select(-c("rt_mean", "rt_sd", "acc_mean", "acc_sd")) %>% 
  mutate(
    trial_type = recode(trial_type,
                        "go" = "Go",
                        "nogo" = "NoGo"),
    rsi = case_when(
      rsi == 0.2 ~ "short",
      rsi == 1 ~ "long"
    ),
    location = factor(location)
  ) %>% 
  select(rsi, trial_type, location, rt, acc, count) %>% 
  mutate(
    location = fct_relevel(location, "C-1", "C", "C+1", "C+2", "E-1", "E", "E+1", "E+2", "baseline")
  ) %>% 
  arrange(rsi, location) %>% 
  filter(location != "baseline") %>% 
  rename(
    "location" = location,
    "RSI" = rsi,
    "trial type" = trial_type,
    "RT" = rt,
    "ACC" = acc
  )

descriptive_analysis_overview_table_robust <- data %>% 
  group_by(rsi, trial_type, error_code) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  mutate(count = acc_count) %>% 
  select(-c("rt_count", "acc_count")) %>% 
  mutate(
    rt_mean = papaja::apa_num(rt_mean),
    rt_sd = papaja::apa_num(rt_sd),
    rt = paste0(rt_mean, " (", rt_sd, ")")
    ) %>% 
  mutate(
    acc_mean = papaja::apa_num(acc_mean, gt1 = FALSE),
    acc_sd = papaja::apa_num(acc_sd, gt1 = FALSE),
    acc = paste0(acc_mean, " (", acc_sd, ")")
    ) %>% 
  select(-c("rt_mean", "rt_sd", "acc_mean", "acc_sd")) %>% 
  mutate(
    error_code = ifelse(is.na(error_code), "other", error_code)
  ) %>% 
  mutate(
    trial_type = recode(trial_type,
                        "go" = "Go",
                        "nogo" = "NoGo"),
    rsi = case_when(
      rsi == 0.2 ~ "short",
      rsi == 1 ~ "long"
    ),
    error_code = case_when(
      error_code == -1 ~ "E-1",
      error_code == 0 ~ "E",
      error_code == 1 ~ "E+1",
      TRUE ~ "other"
    )
  ) %>% 
  select(rsi, trial_type, error_code, rt, acc, count) %>% 
  rename(
    "error-condition" = error_code,
    "RSI" = rsi,
    "trial type" = trial_type,
    "RT" = rt,
    "ACC" = acc
  )
```

```{r descriptive-analysis-overview-plot, cache = TRUE, dependson = 'descriptive-analysis-data', warning = FALSE, eval = TRUE}
descriptive_location_plot_rt <- data %>% 
  group_by(rsi, trial_type, location, distance, nogo_type) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  mutate(count = acc_count,
         distance = ifelse(is.na(distance), 0, distance)) %>% 
  mutate(distance = ifelse(distance == 9, "baseline", as.character(distance))) %>% 
  select(-c("rt_count", "acc_count")) %>% 
  # filter(rsi == 0.2) %>% 
  mutate(distance = factor(distance)) %>%
  mutate(nogo_type = ifelse(nogo_type == "baseline", "C,E", nogo_type)) %>% 
  mutate(distance = fct_relevel(distance, "-1", "0", "1", "2", "baseline")) %>% 
  separate_rows(nogo_type, sep = ",") %>% 
  filter(location != "baseline") %>% 
  # filter(!is.na(rt_mean)) %>% 
  ggplot(
    aes(
      x = distance,
      y = rt_mean,
      group = nogo_type,
      color = nogo_type
    )
  )+
 geom_point(size = 2)+
 geom_line()+
  geom_errorbar(
    aes(
      ymin = rt_mean-(rt_sd/sqrt(count)), 
      ymax = rt_mean+(rt_sd/sqrt(count)), 
      width = 0.2
      )
    )+
scale_color_manual(
    values = c("C" = "forestgreen",
               "E" = "red"),
    name = "NoGo-Accuracy",
    labels = c("Correct", "Error")
  )+
  scale_x_discrete(
    labels = c("-1", "NoGo", "+1", "+2", "baseline - Go")
  )+
  labs(
    x = "Location",
    y = "Response Time",
    caption = "Error bars represent standard errors"
  )+
  facet_wrap(~rsi)

descriptive_location_plot_acc <- data %>% 
  group_by(rsi, trial_type, location, distance, nogo_type) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  mutate(count = acc_count,
         distance = ifelse(is.na(distance), 0, distance)) %>% 
  mutate(distance = ifelse(distance == 9, "baseline", as.character(distance))) %>% 
  select(-c("rt_count", "acc_count")) %>% 
  # filter(rsi == 0.2) %>% 
  mutate(distance = factor(distance)) %>%
  mutate(nogo_type = ifelse(nogo_type == "baseline", "C,E", nogo_type)) %>% 
  mutate(distance = fct_relevel(distance, "-1", "0", "1", "2", "baseline")) %>% 
  separate_rows(nogo_type, sep = ",") %>% 
  filter(location != "baseline") %>% 
  # filter(!is.na(rt_mean)) %>% 
  ggplot(
    aes(
      x = distance,
      y = acc_mean,
      group = nogo_type,
      color = nogo_type
    )
  )+
 geom_point(size = 2)+
 geom_line()+
  geom_errorbar(
    aes(
      ymin = acc_mean-(acc_sd/sqrt(count)), 
      ymax = acc_mean+(acc_sd/sqrt(count)), 
      width = 0.2
      )
    )+
scale_color_manual(
    values = c("C" = "forestgreen",
               "E" = "red"),
    name = "NoGo-Accuracy",
    labels = c("Correct", "Error")
  )+
  scale_x_discrete(
    labels = c("-1", "NoGo", "+1", "+2", "baseline - Go")
  )+
  labs(
    x = "Location",
    y = "Accuracy",
    caption = "Error bars represent standard errors"
  )+
  facet_wrap(~rsi)+
  theme_classic()
```

```{r descriptive-analysis-checking-nogo-effect, eval = FALSE, cache = TRUE, dependson = 'descriptive-analysis-data'}
# Check if answers after correct nogo trials are different than answers after correct go trials
model <- data %>% 
  group_by(id, block) %>% 
  mutate(
    prev_acc = factor(lag(acc)),
    prev_type = factor(lag(trial_type)),
    rsi = factor(rsi)
  ) %>% 
  ungroup() %>% 
  # filter(acc == 1) %>%
  filter(trial_type == "go") %>% 
  lmerTest::lmer(rt ~ prev_acc*rsi*prev_type + (1 + rsi|id), data = .) 

summary(model)
emmeans::emmeans(model, ~prev_acc*rsi*prev_type)
# PES significantly larger if error was commited on nogo trial
```

```{r descriptive-analysis-checking-full-trial-inclusion, eval = FALSE}
data %>% 
  group_by(rsi, block) %>% 
  mutate(prev_acc = lag(acc),
         prev_type = lag(trial_type)) %>% 
  ungroup() %>% 
  count(id, rsi, prev_acc, prev_type) %>% 
  filter(!is.na(prev_acc), !is.na(prev_type)) %>% 
  mutate(quality = ifelse(n < 40, "bad", "good")) %>% 
  count(rsi, prev_acc, prev_type, quality)
```

```{r descriptive-analysis-rt-overview, eval = FALSE}
data %>% 
  group_by(rsi, nogo_type, distance) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  # filter(rsi == 1) %>% 
  filter(!is.na(nogo_type)) %>% 
  ggplot(
    aes(
      x = distance,
      y = rt_mean,
      group = interaction(nogo_type, rsi),
      color = factor(rsi),
      linetype = nogo_type,
      shape = nogo_type
    )
  )+
  geom_point()+
  geom_errorbar(
    aes(
      ymin = rt_mean-(rt_sd/sqrt(rt_count)), 
      ymax = rt_mean+(rt_sd/sqrt(rt_count)), 
      width = 0.2
      )
    )+
  geom_line()

data %>% 
  group_by(rsi, nogo_type, distance) %>% 
  summarize(
    across(c("rt", "acc"),
    list(
      mean = ~mean(., na.rm = TRUE), 
      sd = ~sd(., na.rm = TRUE),
      count = ~n()
      )
    )
  ) %>% 
  # filter(rsi == 1) %>% 
  filter(!is.na(nogo_type)) %>% 
  ggplot(
    aes(
      x = distance,
      y = acc_mean,
      group = interaction(nogo_type, rsi),
      color = factor(rsi),
      linetype = nogo_type,
      shape = nogo_type
    )
  )+
  geom_point()+
  geom_errorbar(
    aes(
      ymin = acc_mean-(acc_sd/sqrt(acc_count)), 
      ymax = acc_mean+(acc_sd/sqrt(acc_count)), 
      width = 0.2
      )
    )+
  geom_line()
```

```{r descriptive-analysis-error-speed-analysis, eval = FALSE}
median_speed_go_correct_short <- data %>% 
  filter(!is.na(rt)) %>% 
  group_by(trial_type, acc, rsi) %>% 
  summarize(median_rt = median(rt, na.rm = TRUE)) %>% 
  filter(acc == 1, trial_type == "go", rsi == 0.2) %>% 
  pull(median_rt)

median_speed_go_correct_long <- data %>% 
  filter(!is.na(rt)) %>% 
  group_by(trial_type, acc, rsi) %>% 
  summarize(median_rt = median(rt, na.rm = TRUE)) %>% 
  filter(acc == 1, trial_type == "go", rsi == 1) %>% 
  pull(median_rt)


data %>% 
  filter(trial_type == "nogo", acc == 0, rsi == 0.2) %>% 
  mutate(
    speed = ifelse(rt > median_speed_go_correct_short, "slower", "faster")
  ) %>% 
  ggplot(
    aes(x = rt,
        group = speed,
        fill = speed)
  )+
  geom_histogram()

data %>% 
  filter(trial_type == "nogo", acc == 0, rsi == 1) %>% 
  mutate(
    speed = ifelse(rt > median_speed_go_correct_long, "slower", "faster")
  ) %>% 
  count(speed)
```


