---
editor_options:
  chunk_output_type: console
---
```{r setup}
# Library calls
library("brms")
library(tidyverse)
library("gridExtra") # for grid.arrange
library("DescTools") # for CCC
```

```{r functions}
# Custom functions

```

```{r data}
# Reading in data
data_robust <- rio::import("./markdown/data/diffusion_data_robust.rdata")

data_model_robust <- rio::import("./markdown/models/brms_wiener_fit.rda")
data_pred_robust <- rio::import("./markdown/models/brms_wiener_predictions.rda")

data_model_robust <- rio::import("./markdown/models/brms_wiener_fit_2023-01-30.rda")
```

```{r checking rhat}
# Checking parameters with highest rhat
data_model_robust$fit %>% 
  rstan::summary() %>% 
  .$summary %>% 
  as_tibble() %>% 
  slice_max(Rhat, n = 5)

data_model_robust$fit %>% 
  rstan::summary() %>% 
  .$summary %>% 
  as_tibble() %>% 
  slice_min(n_eff, n = 5)
```

```{r divergent}
# Number of divergent transitions
sum(subset(nuts_params(data_model_robust), Parameter=="divergent__")$Value)
```

```{r visual-par-inspection}
pars <- variables(data_model_robust)
pars_sel <- c(
  sample(pars[1:(length(pars)/2)], 3),
  sample(pars[-(1:(length(pars)/2))], 3)
  )

plot(data_model_robust, variable = pars_sel, N = 6, 
     ask = FALSE, exact_match = TRUE, newpage = TRUE, plot = TRUE)
```

```{r divergent problems}
pairs(data_model_robust$fit, variable = pars_sel, condition = "divergent__")

```

```{r parameter correlations}
posterior <- as.mcmc(data_model_robust, combine_chains = TRUE)
cor_posterior <- cor(posterior)
cor_posterior[lower.tri(cor_posterior, diag = TRUE)] <- NA
cor_long <- as.data.frame(as.table(cor_posterior))
cor_long <- na.omit(cor_long)
tail(cor_long[order(abs(cor_long$Freq)),], 10)

hist(cor_long$Freq, breaks = 40)
```

```{r model-fit}

```


