---
editor_options:
  chunk_output_type: console
---
# Library calls
```{r setup}
library(tidyverse)
library(rio)
library(data.table)

ggplot2::theme_set(theme_classic()) # setting default theme
```

```{r functions}

```

```{r data}
data <- rio::import("./markdown/data/analysis_data.rdata")
```

# Preparing diffusion model

- keep only pre/post trials or classic pes data set
- make dataset minimal

```{r selecting different datasets}
data_robust <- data %>% 
  filter(error_code %in% c(-1, 1)) %>% 
  select(participant, trial, block,
         trial_type, rsi, 
         acc, rt,
         stimulus, correct, response, decision, decision_char,
         error_code) %>% 
  mutate(
    rsi = case_when(
      rsi == 0.2 ~ "short",
      rsi == 1 ~ "long"
    ),
    error_factor = case_when(
      error_code == -1 ~ "pre_error",
      error_code == 1 ~ "post_error"
    )
  ) %>% 
  mutate(
    rsi = factor(rsi),
    error_factor = factor(error_factor)
  )


data_classic <- data %>% 
  filter(!is.na(classic_pes_type)) %>% 
  select(participant, trial, block,
         trial_type, rsi, 
         acc, rt,
         stimulus, correct, response, decision, decision_char,
         classic_pes_type) %>% 
  mutate(
    rsi = case_when(
      rsi == 0.2 ~ "short",
      rsi == 1 ~ "long"
    )
  ) %>% 
  mutate(
    rsi = factor(rsi),
    error_factor = factor(classic_pes_type)
  )

```

```{r no na}
data_robust_clean <- data_robust %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo")

data_classic_clean <- data_classic %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo")
```

```{r export data}
rio::export(data_classic_clean, "./markdown/data/diffusion_data_classic.rdata")
rio::export(data_robust_clean, "./markdown/data/diffusion_data_robust.rdata")
```

```{r}
data_robust_clean %>% 
  count(participant, rsi, error_code) %>% 
  mutate(quality = ifelse(n > 40, "good", "bad")) %>% 
  ungroup() %>% 
  group_by(error_code, rsi) %>% 
  count(quality)
```

