---
editor_options:
  chunk_output_type: console
---
```{r setup}
# Library calls
library(tidyverse)
library(rio)
library(data.table)

ggplot2::theme_set(theme_classic()) # setting default theme

# Diffusion model packages
library(brms)

# Rstan
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

```{r functions}
# Custom functions

```

```{r data}
# Reading in data
data_robust <- rio::import("./markdown/data/diffusion_data_robust.Rdata")
data_classic <- rio::import("./markdown/data/diffusion_data_classic.rdata")
```

```{r set-formula}
formula <- bf(
  # No intercepts, bc this estimates parameters for each combination of
  # rsi and error_factor
  rt | dec(decision) ~ 0 + rsi:error_factor:stimulus,
    # random slopes just for rsi for now. can do random slopes for error_factor later
    # TODO: Implement this! Model comparison?
  bs ~ 0 + rsi:error_factor,
    # because rsi and error_factor are known they can be used here
    # pre-error is not technically "known", but should affect bs and ndt nonetheless
  ndt ~ 0 + rsi:error_factor,
  bias = 0.5 # no reason for bias to vary TODO: intercept for bias
    # just want to estimate intercept for bias?
    # TODO: maybe estimate intercept for bias? 
)
```

```{r auto-prior}
auto_prior_robust <- get_prior(
  formula,
  data = data_robust,
  family = wiener( # check difference in transformation links in null model
    link = "identity",
    link_bs = "identity",
    link_ndt = "identity",
    link_bias = "identity"
  )
)

auto_prior_classic <- get_prior(
  formula,
  data = data_classic,
  family = wiener(
    link = "identity",
    link_bs = "identity",
    link_ndt = "identity",
    link_bias = "identity"
  )
)

auto_prior_classic_default <- get_prior(
  formula,
  data = data_classic,
  family = wiener(
    link = "identity",
    link_bs = "log",
    link_bias = "logit",
    link_ndt = "log"
  )
)
```

```{r stan-code-check}
# Check that all parameters listed
make_stancode(formula, 
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_robust, 
              prior = auto_prior_robust)

# For classic data
make_stancode(formula, 
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_classic, 
              prior = auto_prior_classic)

# For classic with default
make_stancode(formula, 
              family = wiener(link = "identity",
                              link_bs = "log", 
                              link_ndt = "log",
                              link_bias = "logit"),
              data = data_classic, 
              prior = auto_prior_classic_default)
```


```{r temp-starting-values}
tmp_dat_robust <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_robust,
  prior = auto_prior_robust
  )

tmp_dat_classic <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_classic,
  prior = auto_prior_classic
  )

tmp_dat_classic_default <- make_standata(
  formula, 
  family = wiener(
   link = "identity",
   link_bs = "log", 
   link_ndt = "log",
   link_bias = "logit"
    ),
  data = data_classic,
  prior = auto_prior_classic_default
  )

```

```{r init-function}
initfun_robust <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_robust$K), 
    b_bs = runif(tmp_dat_robust$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_robust$K_ndt, 0.05, 0.1)
  )
}

initfun_classic <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_classic$K), 
    b_bs = runif(tmp_dat_classic$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_classic$K_ndt, 0.05, 0.1)
  )
}

initfun_classic_default <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_classic_default$K), 
    b_bs = runif(tmp_dat_classic_default$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_classic_default$K_ndt, 0.05, 0.1)
  )
}
```

```{r setup-model}
n_iter <- 2000
n_warmup <- 1000
n_chains <- 4
n_cores <- 4
max_depth <- 15
adapt_delta <- 0.95
seed <- 1234
```

```{r fitting-model-classic}
fit_wiener_classic_null <- brm(
  formula, 
  data = data_classic,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = auto_prior_classic, 
  init = initfun_classic,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_classic_null, file = paste0("./markdown/models/null_brms_wiener_fit_classic_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-classic}
fit_wiener_classic_default_null <- brm(
  formula, 
  data = data_classic,
  family = wiener(
    link = "identity",
    link_bs = "log", 
    link_ndt = "log",
    link_bias = "logit"
    ),
  prior = auto_prior_classic_default, 
  init = initfun_classic_default,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_classic_default_null, file = paste0("./markdown/models/null_brms_wiener_fit_classic_default", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-robust}
fit_wiener_robust_null <- brm(
  formula, 
  data = data_robust,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = auto_prior_robust, 
  init = initfun_robust,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-robust}
save(fit_wiener_robust_null, file = paste0("./markdown/models/null_brms_wiener_fit_robust_", Sys.Date(), ".rda"),
     compress = "xz")
```