---
title             : |
  Bachelor Thesis:
  
  The Nature of Cognitive Processes Underlying Post-Error Slowing – A Diffusion Model Account
shorttitle        : "Nature of Post-Error Slowing"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Im Neuenheimer Feld 695, 69120 Heidelberg"
    email         : "sven.lesche@stud.uni-heidelberg.de"
    # role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
  # - name          : "1. Betreuerin: Kathrin Sadus"
  #   affiliation   : "1"
  # - name          : "2. Betreuer: Dirk Hagemann"
  #   affiliation   : "1"
    # role:
    #   - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  # - id            : "2"
  #   institution   : "Konstanz Business School"
  # add a second id using this syntax

authornote: |
  \begin{center}
  \begin{tabular}{rl}
  Author: &Sven Lesche \\
  
  Matrikel-Nr: &4171783 \\
  
  First supervisor: &Kathrin Sadus \\
  
  Second supervisor: &Dirk Hagemann \\
  \end{tabular}
  \end{center}
  
  This work represents the author's bachelor-thesis. It was completed in R-Markdown with the code for data preparation, analysis and communication integrated into the scripts. All code needed to replicate this exact work can be found at: https://github.com/SLesche/bachelor. The author acknowledges support by the state of Baden-Württemberg through bwHPC.

abstract: |
  Post-error slowing (PES) refers to increased response times on trials following errors, often accompanied by changes in accuracy. Theories explaining post-error effects propose adaptive or maladaptive processes. Adaptive processes, like heightened caution, enhance accuracy following errors. Maladaptive processes, such as decreased attention, reduce accuracy. This study aims to examine how the response-stimulus interval (RSI) influences the relative strength of adaptive and maladaptive processes after error trials using Bayesian hierarchical Drift-Diffusion Models (DDM).

  We employed a motor-inhibition Go-NoGo task with 93 participants (77 females, M = 21.37, SD = 2.50 years old) completing 1500 trials each in a short (200 ms) and a long (1000 ms) RSI condition. Results show increased response time and decreased accuracy following errors, particularly in the short RSI condition. The DDM does not adequately fit data in the short RSI condition due to a censored response-time distribution in post-error trials. In the long RSI condition, drift rate, boundary separation and non-decision time all decreased following errors.

  Behavioral findings suggest more significant attentional deficits after errors in the short RSI condition, indicating higher impact of maladaptive processes. DDM results in the long RSI condition support the notion of reduced caution and attention following errors, indicative of post-error recklessness. However, concerns regarding task design raise strong doubts about the validity of the DDM parameters obtained in this study.

  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "post-error slowing, response-stimulus interval, diffusion modeling, adaptive account, maladaptive account"

bibliography      : ["r-references.bib", "clean_pes_lib.bib"]

floatsintext      : yes # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")

knitr::opts_chunk$set(cache = FALSE)
# Seed for random number generation
set.seed(12345)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::dep_auto()

# disable all in-document warnings
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

<!-- Setup -->
```{r child = "markdown/setup.Rmd"}
```
<!-- Here we incorporate child markdown-documents as the separate parts -->

<!-- Introduction -->
```{r child = "markdown/introduction.Rmd", eval = TRUE}
```

<!-- Method -->
```{r child = "markdown/method.Rmd", eval = TRUE}
```


<!-- Results -->
```{r child = "markdown/results.Rmd", eval = TRUE}
```


<!-- Discussion -->
```{r child = "markdown/discussion.Rmd", eval = TRUE}
```


<!-- References -->
\newpage
# References
::: {#refs custom-style="Bibliography"}
:::

\newpage

# (APPENDIX) Appendix {-}

```{r child = "markdown/appendix.Rmd", eval = TRUE}
```

