<!-- This file is for LaTeX and R setups -->
<!-- Latex -->
<!-- Problem with Latex stuff is, that it won't compile to word correctly... -->

<!-- R -->

```{r setup-libraries}
# think about calling renv here to make sure everyone has the same packages installed

library(papaja)
library(tidyverse)
library(Superpower)
library(rio)
library(flextable)
library(ftExtra)
library(rmarkdown)
library(knitr)
library(brms)
library(loo)
library(tidybayes)
library(lme4)

r_refs("./markdown/r-references.bib")

r_citations <- cite_r(
  file = "r-references.bib",
  pkgs = c("papaja", "tidyverse", "knitr", "afex", "loo", "lme4", "emmeans", "brms", "tidybayes"),
  omit = FALSE,
  footnote = TRUE
  )

```

```{r setup-tinytex}
# want to auto-install tinytex 
# if(tinytex::is_tinytex() == FALSE){
#   tinytex::install_tinytex()
# }
```

```{r setup-analysis-preferences}
# set flextable defaults for fonts
set_flextable_defaults(fonts_ignore = TRUE)
```

```{r setup-transpose-function}
df_transpose <- function(df) {
  
  first_name <- colnames(df)[1]
  
  temp <-
    df %>% 
    tidyr::pivot_longer(-1) %>%
    tidyr::pivot_wider(names_from = 1, values_from = value)
  
  colnames(temp)[1] <- first_name
  temp
}
```

```{r setup-apa-footer-flextable}
apa_footer <- function(data, note){
  flextable::add_footer_lines(
    x = data,
    " "
    ) %>%
    flextable::compose(
      # x = data,
      i = 1,
      j = 1,
      part = "footer",
      value = as_paragraph(
        as_i("Note. "), note
      )
    )
}
```

```{r setup-print-flextable}
print_flextable_apa <- function(x){
  flextable::flextable_to_rmd(
    x,
    ft.align = "left",
    ft.keepnext = TRUE,
    bookdown = TRUE,
    print = TRUE
  )
}
```

```{r setup-print-cohen}
print_cohen <- function(x, ci = FALSE){
  estimate = round(x$estimate, 2)
  ci_lower = round(x$conf.int[1], 2)
  ci_upper = round(x$conf.int[2], 2)
  if (estimate < 0){
    estimate = estimate * -1
    ci_lower_copy = ci_lower
    ci_upper_copy = ci_upper
    ci_upper = ci_lower_copy * -1
    ci_lower = ci_upper_copy * -1 
  }
  
  if (ci == TRUE){
    message = paste0(
      "$d = ",
      estimate,
      "$, ",
      "95\\% CI $",
      "[",
      ci_lower,
      ", ",
      ci_upper,
      "]$"
    )
  } else {
    message = paste0(
      "$d = ",
      estimate,
      "$"
    )
  }
  
  return(message)
}

print_mean_cohen <- function(x, y){
  estimate_x = abs(round(x$estimate, 2))
  estimate_y = abs(round(y$estimate, 2))
  
  mean = round(mean(c(estimate_x, estimate_y)), 2)
  
  message = paste0(
    "$\\mu_{d} = ",
    mean,
    "$"
  )
  
  return(message)
}

print_cohen_num <- function(x){
  round = round(x, 2)
   message = paste0(
      "$d = ",
      round,
      "$"
    )
  return(message)
}

print_scientific <- function(num){
  num = round(num, 2)
  if (num < 0.01 | num > 1000){
    science_num = format(num, scientific = TRUE)
    char_num = stringr::str_replace(science_num, "e?[\\+\\-]\\d(\\d)", "\\\\times 10^{\\1}")
  } else {
    char_num = paste(num)
  }
  
  return(char_num)
}

print_bf <- function(bf_result){
  bf = exp(bf_result$log_BF)
  if (bf < 1){
    bf_prefix = "BF_{01} = "
  } else {
    bf_prefix = "BF_{10} = "
  }

  if (bf < 1000 & bf > 0.01){
    bf_rounded = round(bf, 2)
    bf_print = paste0("$", bf_prefix, bf_rounded, "$")
  } else {
    bf_exp = floor(log(bf, 10))
    bf_base = format(bf, scientific = TRUE)
    bf_base_str = stringr::str_remove(bf_base, "e[+-]\\d{2}$")
    bf_base_str = paste0(round(as.numeric(bf_base_str), 2))
    bf_exp_str = paste0(bf_base_str, " \\times 10^{", bf_exp, "}")
    bf_print = paste0("$", bf_prefix, bf_exp_str, "$")
  }
  return(bf_print)
}
```

