---
editor_options:
  chunk_output_type: console
---
# Library calls
```{r setup}
library(tidyverse)
library(rio)
library(data.table)
library(afex)
library(emmeans)
library(lme4) # for later
library(broom)

ggplot2::theme_set(theme_classic()) # setting default theme
```

```{r functions}

```

```{r data}
data <- rio::import("./markdown/data/analysis_data.Rdata") %>% 
  mutate(rsi = factor(rsi),
         error_code = factor(error_code),
         id = factor(id))
```

```{r notes}
# TODO
# RT short vs. long
# Condition Comparison
# RT error types
# RT classic PES version
# Interaction RSI X Error_type on RT

# ACC short vs. long
# ACC pre. vs. post-error
# Interaction RSI x Error_type on ACC


```

```{r assumption-checks}
# Check assumptions_checks.rmd 
# Assumption of homogeneity of variance violated in factors rsi/error_code
```

```{r condition}
data %>% 
  filter(trial_type == "go") %>% 
  group_by(id, map_condition) %>% 
  summarize(mean_rt = mean(rt, na.rm = TRUE)) %>% 
  t.test(mean_rt ~ map_condition, data = .) %>% 
  broom::tidy()

# Condition has significant effect on rt

data %>% 
  filter(trial_type == "go") %>% 
  group_by(id, map_condition) %>% 
  summarize(mean_acc = mean(acc, na.rm = TRUE)) %>% 
  t.test(mean_acc ~ map_condition, data = .) %>% 
  broom::tidy()

# But not on acc

# Interaction condition and pes?
data %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  group_by(id, map_condition, error_code) %>% 
  summarize(
    across(
      c("rt", "acc"),
      list(mean = ~mean(., na.rm = TRUE), sd = ~sd(., na.rm = TRUE))
    )
  ) %>% 
  filter(error_code %in% c(-1, 1)) %>% 
  group_by(id, map_condition) %>% 
  summarize(pes = rt_mean - lag(rt_mean),
            pea = acc_mean - lag(acc_mean)) %>% 
  filter(!is.na(pes)) %>% 
  ungroup() %>% 
  # t.test(pea ~ map_condition, data = .)
  t.test(pes ~ map_condition, data = .)

```

```{r rsi-error-code}
mean_data_rsi_robust <- data %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  group_by(id, rsi, error_code) %>%
  summarize(
    across(
      c("rt", "acc"),
      list(mean = ~mean(., na.rm = TRUE), sd = ~sd(., na.rm = TRUE))
    )
  ) %>%
  filter(error_code %in% c(-1, 1)) %>% 
  ungroup() %>% 
  mutate(id = factor(id),
         rsi = factor(rsi, 
                      levels = c(0.2, 1),
                      labels = c("short", "long")),
         error_code = factor(error_code,
                             levels = c(-1, 1),
                             labels = c("pre-error", "post-error"))
         )

mean_data_rsi_classic <- data %>% 
  filter(!is.na(rt) & trial_type == "go" | trial_type == "nogo") %>% 
  group_by(id, rsi, classic_pes_type) %>%
  summarize(
    across(
      c("rt", "acc"),
      list(mean = ~mean(., na.rm = TRUE), sd = ~sd(., na.rm = TRUE))
    )
  ) %>%
  filter(!is.na(classic_pes_type)) %>% 
  ungroup() %>% 
  mutate(id = factor(id),
         rsi = factor(rsi, 
                      levels = c(0.2, 1),
                      labels = c("short", "long")),
         classic_pes_type = factor(classic_pes_type)
         )

aov_rt_rsi_error_robust <- aov_car(
  formula = rt_mean ~ rsi*error_code + Error(id/rsi*error_code),
  data = mean_data_rsi_robust,
  anova_table = list(es = c("ges","pes"))
)

aov_rt_rsi_error_classic <- aov_car(
  formula = rt_mean ~ rsi*classic_pes_type + Error(id/rsi*classic_pes_type),
  data = mean_data_rsi_classic,
  anova_table = list(es = c("ges","pes"))
)

aov_acc_rsi_error_robust <- aov_car(
  formula = acc_mean ~ rsi*error_code + Error(id/rsi*error_code),
  data = mean_data_rsi_robust,
  anova_table = list(es = c("ges","pes"))
)

aov_acc_rsi_error_classic <- aov_car(
  formula = acc_mean ~ rsi*classic_pes_type + Error(id/rsi*classic_pes_type),
  data = mean_data_rsi_classic,
  anova_table = list(es = c("ges","pes"))
)
```

```{r emmeans}
aov_rt_rsi_error_robust %>% 
  emmeans(~error_code*rsi)

aov_rt_rsi_error_classic %>% 
  emmeans(~classic_pes_type*rsi)

aov_acc_rsi_error_robust %>% 
  emmeans(~error_code*rsi)

aov_acc_rsi_error_classic %>% 
  emmeans(~classic_pes_type*rsi)
```

```{r papaja-example}
papaja::apa_print(
  aov_rt_rsi_error_classic
)
```

```{r linear-models}
# Multilevel models allow incorporating the full range of rts
lm_rt_robust <- lmer(
  rt ~ rsi*error_code + (1 + rsi|id),
  data = data
)
summary(lm_rt_robust)

lm_rt_classic <- lmer(
  rt ~ rsi*classic_pes_type + (1 + rsi|id),
  data = data
)
summary(lm_rt_classic)
```

