---
editor_options:
  chunk_output_type: console
---
```{r setup}
# Library calls
library(tidyverse)
library(rio)
library(data.table)

ggplot2::theme_set(theme_classic()) # setting default theme

# Diffusion model packages
library(brms)

# Rstan
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

```{r functions}
# Custom functions

```

```{r data}
# Reading in data
data <- rio::import("./markdown/data/analysis_data.rdata")
data_robust <- rio::import("./markdown/data/diffusion_data_robust.Rdata")
data_classic <- rio::import("./markdown/data/diffusion_data_classic.rdata")
```

```{r prepping data}
data_vibes <- data %>%
  select(id, trial, block, map_condition,
         trial_type, rsi, 
         acc, rt,
         stimulus, correct, response, decision, decision_char) %>% 
  mutate(
    rsi = case_when(
      rsi == 0.2 ~ "short",
      rsi == 1 ~ "long"
    ),
    stimulus = case_when(
      stimulus == "X" ~ 0,
      stimulus == "Y" ~ 1
    )
  ) %>% 
  mutate(
    rsi = factor(rsi),
    map_condition = factor(map_condition),
    stimulus = factor(stimulus)
  ) %>% 
  group_by(id, block) %>% 
  mutate(
    next_nogo = case_when(
      lead(trial_type) == "nogo" & trial_type == "go" & lead(acc) == 1 ~ "pre_correct",
      lead(trial_type) == "nogo" & trial_type == "go" & lead(acc) == 0 ~ "pre_error"
    ),
    rt = rt/1000
  ) %>% 
  ungroup() %>% 
  mutate(
    next_nogo = factor(next_nogo)
  ) %>% 
  filter(!is.na(next_nogo)) %>% 
  filter(trial_type == "go", acc == 1)
```

```{r formula}
formula_null <- bf(
  rt | dec(decision) ~ 0 + next_nogo:stimulus,
  bs ~ 0 + next_nogo,
  ndt ~ 0 + next_nogo,
  bias = 0.5
)

formula_rsi <- bf(
  rt | dec(decision) ~ 0 + rsi:next_nogo:stimulus,
  bs ~ 0 + rsi:next_nogo,
  ndt ~ 0 + rsi:next_nogo,
  bias = 0.5
)

```

```{r prior}
prior <- c(
  # drift rate
 prior("cauchy(0, 5)", class = "b"), # drift rate, population

 # boundary separation
 set_prior("normal(1.5, 1)", class = "b", dpar = "bs", lb = 0), 
  # bs restricted to > 0, lb = 0

 # Non-decision time
 set_prior("normal(0.15, 0.1)", class = "b", dpar = "ndt", lb = 0)
)
```

```{r}
tmp_dat_null <- make_standata(
  formula_null, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_vibes,
  prior = prior
  )

tmp_dat_rsi <- make_standata(
  formula_rsi, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_vibes,
  prior = prior
  )
```

```{r}
initfun_null <- function(){
  list(
    b = rnorm(tmp_dat_null$K), 
    b_bs = runif(tmp_dat_null$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_null$K_ndt, 0.05, 0.1)
  )
}

initfun_rsi <- function(){
  list(
    b = rnorm(tmp_dat_rsi$K), 
    b_bs = runif(tmp_dat_rsil$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_rsi$K_ndt, 0.05, 0.1)
  )
}
```

```{r model-spec}
n_iter <- 2000
n_warmup <- 1000
n_chains <- 4
n_cores <- 4
max_depth <- 15
adapt_delta <- 0.95
seed <- 1234
```

```{r fitting-model-null}
fit_wiener_vibes_null <- brm(
  formula_null, 
  data = data_vibes,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_null,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_nogo_null, file = paste0("./markdown/models/vibes_standard_type_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-rsi}
fit_wiener_vibes_rsi <- brm(
  formula_rsi, 
  data = data_vibes,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_rsi,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_nogo_rsi, file = paste0("./markdown/models/vibes_standard_type_rsi_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-null}
fit_wiener_nogo_rsi_acc <- brm(
  formula_rsi_acc, 
  data = data_nogo,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_rsi_acc,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_nogo_rsi_acc, file = paste0("./markdown/models/rsi_acc_brms_wiener_fit_nogo_", Sys.Date(), ".rda"),
     compress = "xz")
```
