---
editor_options:
  chunk_output_type: console
---
```{r setup}
library(tidyverse)
library(rio)
library(data.table)

ggplot2::theme_set(theme_classic()) # setting default theme

# Diffusion model packages
library(brms)

# Rstan
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

```

```{r functions}

```

```{r data}
data_robust <- rio::import("./markdown/data/diffusion_data_robust.Rdata")
data_classic <- rio::import("./markdown/data/diffusion_data_classic.rdata")
data_location <- rio::import("./markdown/data/diffusion_data_location.rdata")
```

```{r testing intercepts}
# Have to supress intercept for modeling reasons (that I don't quite understand myself)
# And combining factors with `:` gives each combination an estimate
unique(model.matrix(~ 0 + rsi:error_factor:stimulus, data_classic))
unique(model.matrix(~ 0 + rsi*error_factor, data_robust))
unique(model.matrix(~ 0 + rsi:error_factor, data_robust))
unique(model.matrix(~ 1 + rsi*error_factor, data_robust))
```

```{r set-formula}
# Add no intercorr here ||
formula <- bf(
  # No intercepts, bc this estimates parameters for each combination of
  # rsi and error_factor
  rt | dec(decision) ~ 0 + rsi:error_factor:stimulus + (0 + rsi:error_factor:stimulus|id),
    # random slopes just for rsi for now. can do random slopes for error_factor later
    # TODO: Implement this! Model comparison?
  bs ~ 0 + rsi:error_factor + (0 + rsi:error_factor|id),
    # because rsi and error_factor are known they can be used here
    # pre-error is not technically "known", but should affect bs and ndt nonetheless
  ndt ~ 0 + rsi:error_factor + (0 + rsi:error_factor|id),
  bias = 0.5 # no reason for bias to vary TODO: intercept for bias
    # just want to estimate intercept for bias?
    # TODO: maybe estimate intercept for bias? 
)
```

```{r set-prior}
prior <- c(
 # correlation
 prior("lkj(1)", class = "cor"), # max uninformative correlation prior
 # drift rate
 prior("cauchy(0, 5)", class = "b"), # drift rate, population

 # boundary separation
 set_prior("normal(1.5, 1)", class = "b", dpar = "bs", lb = 0), 
  # bs restricted to > 0, lb = 0
 
 # Non-decision time
 set_prior("normal(0.15, 0.1)", class = "b", dpar = "ndt", lb = 0),
 
 # Group-level
 set_prior("normal(0, 0.3)", class = "sd")
)
```

```{r stan-code-check}
# Check that all parameters listed
make_stancode(formula, # default transformations
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_robust, 
              prior = prior)

# For classic data
make_stancode(formula, 
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_classic, 
              prior = prior)
```

```{r temp-starting-values}
tmp_dat_robust <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_robust,
  prior = prior
  )

tmp_dat_classic <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_classic,
  prior = prior
  )

tmp_dat_location <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_location,
  prior = prior
  )
```

```{r init-function}
initfun_robust <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_robust$K), 
    b_bs = runif(tmp_dat_robust$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_robust$K_ndt, 0.05, 0.1), # rep for each dim in ndt
    sd_1 = runif(tmp_dat_robust$M_1, 0.5, 1),
    z_1 = matrix(rnorm(tmp_dat_robust$M_1*tmp_dat_robust$N_1, 0, 0.01),
                 tmp_dat_robust$M_1, tmp_dat_robust$N_1),
    L_1 = diag(tmp_dat_robust$M_1),
    sd_2 = runif(tmp_dat_robust$M_2, 0.5, 1),
    z_2 = matrix(rnorm(tmp_dat_robust$M_2*tmp_dat_robust$N_2, 0, 0.01),
                 tmp_dat_robust$M_2, tmp_dat_robust$N_2),
    L_2 = diag(tmp_dat_robust$M_2),
    sd_3 = runif(tmp_dat_robust$M_3, 0.5, 1),
    z_3 = matrix(rnorm(tmp_dat_robust$M_3*tmp_dat_robust$N_3, 0, 0.01),
                 tmp_dat_robust$M_3, tmp_dat_robust$N_3),
    L_3 = diag(tmp_dat_robust$M_3)
  )
}

initfun_classic <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_classic$K),
    b_bs = runif(tmp_dat_classic$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_classic$K_ndt, 0.05, 0.1), # rep for each dim in ndt
    sd_1 = runif(tmp_dat_classic$M_1, 0.5, 1),
    z_1 = matrix(rnorm(tmp_dat_classic$M_1*tmp_dat_classic$N_1, 0, 0.01),
                 tmp_dat_classic$M_1, tmp_dat_classic$N_1),
    L_1 = diag(tmp_dat_classic$M_1),
    sd_2 = runif(tmp_dat_classic$M_2, 0.5, 1),
    z_2 = matrix(rnorm(tmp_dat_classic$M_2*tmp_dat_classic$N_2, 0, 0.01),
                 tmp_dat_classic$M_2, tmp_dat_classic$N_2),
    L_2 = diag(tmp_dat_classic$M_2),
    sd_3 = runif(tmp_dat_classic$M_3, 0.5, 1),
    z_3 = matrix(rnorm(tmp_dat_classic$M_3*tmp_dat_classic$N_3, 0, 0.01),
                 tmp_dat_classic$M_3, tmp_dat_classic$N_3),
    L_3 = diag(tmp_dat_classic$M_3)
  )
}

initfun_location <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_location$K),
    b_bs = runif(tmp_dat_location$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_location$K_ndt, 0.05, 0.1), # rep for each dim in ndt
    sd_1 = runif(tmp_dat_location$M_1, 0.5, 1),
    z_1 = matrix(rnorm(tmp_dat_location$M_1*tmp_dat_location$N_1, 0, 0.01),
                 tmp_dat_location$M_1, tmp_dat_location$N_1),
    L_1 = diag(tmp_dat_location$M_1),
    sd_2 = runif(tmp_dat_location$M_2, 0.5, 1),
    z_2 = matrix(rnorm(tmp_dat_location$M_2*tmp_dat_location$N_2, 0, 0.01),
                 tmp_dat_location$M_2, tmp_dat_location$N_2),
    L_2 = diag(tmp_dat_location$M_2),
    sd_3 = runif(tmp_dat_location$M_3, 0.5, 1),
    z_3 = matrix(rnorm(tmp_dat_location$M_3*tmp_dat_location$N_3, 0, 0.01),
                 tmp_dat_location$M_3, tmp_dat_location$N_3),
    L_3 = diag(tmp_dat_location$M_3)
  )
}
```

```{r setup-model}
n_iter <- 2000
n_warmup <- 1000
n_chains <- 4
n_cores <- 4
max_depth <- 15
adapt_delta <- 0.95
seed <- 1234

model_setup_values <- data.frame(n_iter, n_warmup, n_chains, n_cores, max_depth,
                                 adapt_delta, seed)
```

```{r fitting-model-location}
fit_wiener_location <- brm(
  formula, 
  data = data_location,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_location,
  iter = n_iter, 
  # init_r = 0.1,
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  # control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_location, file = paste0("./markdown/models/full_effect_location_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-classic}
fit_wiener_classic <- brm(
  formula, 
  data = data_classic,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_classic,
  iter = n_iter, 
  # init_r = 0.1,
  warmup = n_warmup, 
  chains = 1,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_classic, file = paste0("./markdown/models/brms_wiener_fit_classic_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-robust}
fit_wiener_robust_depth <- brm(
  formula, 
  data = data_robust,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_robust,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
# Can run %>% add_loo() here for added model fit parameters? only relevant for model comparison?
```

```{r saving-ddm-robust}
save(fit_wiener_robust, file = paste0("./markdown/models/test_wiener_fit_robust_", Sys.Date(), ".rda"),
     compress = "xz")
```
