---
editor_options:
  chunk_output_type: console
---
```{r setup}
library(tidyverse)
library(rio)
library(data.table)

ggplot2::theme_set(theme_classic()) # setting default theme

# Diffusion model packages
library(brms)

# Rstan
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

```

```{r functions}

```

```{r data}
data_robust <- rio::import("./markdown/data/diffusion_data_robust.Rdata")
data_classic <- rio::import("./markdown/data/diffusion_data_classic.rdata")
```

```{r formula}
formula <- bf(
  # No intercepts, bc this estimates parameters for each combination of
  # rsi and error_factor
  rt | dec(decision) ~ 0 + rsi:error_factor:stimulus,
    # TODO: Implement this! Model comparison?
  bs ~ 0 + rsi:error_factor,
    # because rsi and error_factor are known they can be used here
    # pre-error is not technically "known", but should affect bs and ndt nonetheless
  ndt ~ 0 + rsi:error_factor,
  bias = 0.5 # no reason for bias to vary TODO: intercept for bias
    # just want to estimate intercept for bias?
    # TODO: maybe estimate intercept for bias? 
)
```

```{r testing intercepts}
# Have to supress intercept for modeling reasons (that I don't quite understand myself)
# And combining factors with `:` gives each combination an estimate
unique(model.matrix(~ 0 + rsi:error_factor:stimulus, data_classic))
unique(model.matrix(~ 0 + rsi*error_factor, data_robust))
unique(model.matrix(~ 1 + rsi:error_factor:stimulus, data_robust))
unique(model.matrix(~ 0 + rsi:error_factor, data_robust))
```
```{r set-prior}
prior <- c(
 # drift rate
 prior("cauchy(0, 5)", class = "b"), # drift rate, population

 # boundary separation
 set_prior("normal(1.5, 1)", class = "b", dpar = "bs", lb = 0), 
  # bs restricted to > 0, lb = 0
 
 # Non-decision time
 set_prior("normal(0.15, 0.1)", class = "b", dpar = "ndt", lb = 0)
)
```

```{r stan-code-check}
# Check that all parameters listed
make_stancode(formula, # default transformations
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_robust, 
              prior = prior)

# For classic data
make_stancode(formula, 
              family = wiener(link_bs = "identity", 
                              link_ndt = "identity",
                              link_bias = "identity"),
              data = data_classic, 
              prior = prior)
```

```{r temp-starting-values}
tmp_dat_robust <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_robust,
  prior = prior
  )

tmp_dat_classic <- make_standata(
  formula, 
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  data = data_classic,
  prior = prior
  )

```

```{r init-function}
initfun_robust <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_robust$K), 
    b_bs = runif(tmp_dat_robust$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_robust$K_ndt, 0.05, 0.1)
  )
}

initfun_classic <- function() {# all pars in stancode need init here
  list(
    b = rnorm(tmp_dat_classic$K),
    b_bs = runif(tmp_dat_classic$K_bs, 1, 2),
    b_ndt = runif(tmp_dat_classic$K_ndt, 0.05, 0.1)
  )
}
```

```{r setup-model}
n_iter <- 4000
n_warmup <- 2000
n_chains <- 4
n_cores <- 4
max_depth <- 15
adapt_delta <- 0.95
seed <- 1234

model_setup_values <- data.frame(n_iter, n_warmup, n_chains, n_cores, max_depth,
                                 adapt_delta, seed)
```

```{r fitting-model-classic}
fit_wiener_classic <- brm(
  formula, 
  data = data_classic,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_classic,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 20,
  seed = seed # reproducibility
  )
```

```{r saving-ddm-classic}
save(fit_wiener_classic, file = paste0("./markdown/models/classic_standard_rsi_err_", Sys.Date(), ".rda"),
     compress = "xz")
```

```{r fitting-model-robust}
fit_wiener_robust <- brm(
  formula, 
  data = data_robust,
  family = wiener(
    link_bs = "identity", 
    link_ndt = "identity",
    link_bias = "identity"
    ),
  prior = prior, 
  init = initfun_robust,
  iter = n_iter, 
  warmup = n_warmup, 
  chains = n_chains,
  cores = n_cores, 
  control = list(max_treedepth = max_depth, adapt_delta = adapt_delta),
  refresh = 100,
  seed = seed # reproducibility
  )
# Can run %>% add_loo() here for added model fit parameters? only relevant for model comparison?
```

```{r saving-ddm-robust}
save(fit_wiener_robust, file = paste0("./markdown/models/robust_standard_rsi_err", Sys.Date(), ".rda"),
     compress = "xz")
```
